### ISSUE TITLE
Cache doesn't work on CircleCI

### ISSUE THREAD

**Issue by nqtien310** [oesmith/puffing-billy#100]
I'm using puffing-billy for stubbing a form which directly uploads a file to Amazon S3 . This works perfectly fine on my localhost , 2 .yml files are generated ( 1 for preflight Options method & 1 for Post method ).

But when I checked-in & pushed those 2 .yml files to CircleCi and run the specs, somehow it doesn't work . Do I miss any configuration to make the Cache work on CircleCI ?

Any help or suggestion are appreciated.

Best regards.

**Comment by ronwsmith** [comment]
Puffing-billy only caches requests coming from the browser.  I suspect that your back-end is performing external requests as well, so you probably need to also include VCR to cache those interactions.

**Comment by nqtien310** [comment]
Hi Ronswmith, thanks for your answer but I don't think it explains why the specs passed on my local but doesn't passed on CircleCI with same configurations ?

**Comment by ronwsmith** [comment]
Yes, it would.  Your local environment likely has internet access.  That's speculation though.  What's the specific error you're receiving?

**Comment by ronwsmith** [comment]
@nqtien310, are you still having this issue with v0.6.1?  There is updated VCR config in the README now if you'd like to try using them together to cache both browser and back-end calls.

**Comment by ronwsmith** [comment]
Closing -- stale issue.  I am currently using puffing-billy on CircleCI so it's not a global issue there.
