### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by seanarnold** [oesmith/puffing-billy#101]
I'm not sure if this is a bug or me implementing it wrong but my HTTP calls aren't being cached by Bully.

I'm using Ruby 2.2, Rails 4.2.0.
I have model spec which is testing a method that loads a website and parses some data from it using Phantom JS + Nokogiri. I want to use Bully to cache this interaction.

At the moment the spec passes fine, but Bully isn't caching. In fact I'm not sure if Bully is being used at all, because when I set `non_whitelisted_requests_disabled = true` the spec still passes.

In `rails_helper.rb` I have the following:

```
require 'billy/rspec'

Capybara.javascript_driver = :poltergeist_billy

Billy.configure do |c|
  c.cache = true
  c.cache_request_headers = false
  c.ignore_params = ["http://www.google-analytics.com/__utm.gif",
                     "https://r.twimg.com/jot",
                     "http://p.twitter.com/t.gif",
                     "http://p.twitter.com/f.gif",
                     "http://www.facebook.com/plugins/like.php",
                     "https://www.facebook.com/dialog/oauth",
                     "http://cdn.api.twitter.com/1/urls/count.json"]
  c.path_blacklist = []
  c.persist_cache = true
  c.ignore_cache_port = true # defaults to true
  c.non_successful_cache_disabled = false
  c.non_successful_error_level = :warn
  c.non_whitelisted_requests_disabled = false
  c.cache_path = 'spec/req_cache/'
end
```

My spec is simple, as I'm trying to get caching working with the minimum amount of code to start:
```
it 'should attempt to parse the data', :js => true  do
    subject
end
```

What am I doing wrong here?

**Comment by ronwsmith** [comment]
Your setup looks fine.  What URL are you hitting?  Anything in the billy logs?

**Comment by seanarnold** [comment]
I can't see any Bully logs, only `test.log` and `development.log`.

In `test.log` however I see `puffing-billy: Proxy listening on http://localhost:57202`.
The URL I'm calling is `https://www.nzx.com/markets/NZSX/securities/AIR`

**Comment by ronwsmith** [comment]
That's the log I was talking about -- all logging statements from puffing-billy are prefixed with that.

Looks like it's running fine.  Does anything different happen if you use selenium_billy?  Is a browser opening up?  What is your subject defined as?

**Comment by seanarnold** [comment]
My subject is loading a website using Watir (https://github.com/watir/watir-webdriver) like so:

```
def load_website
    b = Watir::Browser.new(:phantomjs)
    b.goto "#{website_prefix}#{code}#{website_suffix}"
    @page = Nokogiri::HTML(b.html)
end
```

I guess Billy isn't capturing the Watir HTTP requests

**Comment by ronwsmith** [comment]
Ah ha, yes that is the issue.  You are using phantomjs directly in Watir so you are bypassing Capybara and Poltergeist.

**Comment by seanarnold** [comment]
Cool, i might switch back to Capybara + Phantom JS and try again. thanks for your help :)

**Comment by seanarnold** [comment]
Ok so I've changed my code to use Capybara.

```
  Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(app, js_errors: false)
  end

  Capybara.default_driver = :poltergeist

```

```

  def load_website
    b = Capybara.current_session
    b.visit "#{website_prefix}#{code}#{website_suffix}"
    @page = Nokogiri::HTML(b.html)
  end
```

But no cache and no puffing-billy in test.log :(

I;m clearly doing something wrong. Do you have a sample app i could clone and compare?

**Comment by ronwsmith** [comment]
You need to use the poltergeist_billy driver instead of registering your own.  Also with Capybara, you don't need to have that first line in your load_website method.

**Comment by seanarnold** [comment]
Got it working!
I had to set both the javascript_driver and default_driver to poltergeist_billy like below:

```
Capybara.javascript_driver = :poltergeist_billy
Capybara.default_driver = :poltergeist_billy
```

Is there any way to lower the log level so my rspec logs aren't huge?

**Comment by ronwsmith** [comment]
Great!  You can change your overall test environment logging level and it should affect puffing-billy's logs as well.  Closing out this issue.

**Comment by seanarnold** [comment]
Thanks @ronwsmith. I suggest changing the `README` to add the config to `rails_helper.rb` instead as `spec_helper.rb` since RSpec now loads `spec_helper` before Rails using the default Rspec generator.

**Comment by ronwsmith** [comment]
Good idea, done: https://github.com/oesmith/puffing-billy/commit/a4ae4d9cd043ccbc65fb69abded47f0ac51f0710
