### ISSUE TITLE
Logging when not using rails

### ISSUE THREAD

**Issue by devanoff11** [oesmith/puffing-billy#102]
https://github.com/oesmith/puffing-billy/blob/master/lib/billy/config.rb#L16
When not using rails everything is just logged to std out causing tests to output pages of info/warn lines while running.

Would be nice if they were logged somewhere else.

**Comment by mcgeachie** [comment]
Yes it would.

**Comment by mcgeachie** [comment]
You can adjust the log level by passing a Logger value into logger.level in your Billy config if that helps?

**Comment by ronwsmith** [comment]
Changing log level should be enough for this issue right now.
