### ISSUE TITLE
json response causes parse error in firefox

### ISSUE THREAD

**Issue by vbyjsue** [oesmith/puffing-billy#103]
I'm interested if anyone else have experienced this problem and how to solve it. 
When I try to stub a request and return json it works fine in chrome but firefox can't handle the response:
"SyntaxError: JSON.parse: unexpected end of data at line 1column 1 of the JSON data"

Tried with firefox 35 and 37.
Here's the code i'm using:
proxy.stub("#{$jupiter_url}:443/player/sessions", :method => 'post').and_return(:code => 400, :json => {"error" => {"code" => 5}})

Using the :selenium_billy driver
Maybe there is something i'm doing wrong?

**Comment by ronwsmith** [comment]
Hmm, looks fine.  Can you pry before the error and see what JSON is being received?  How are you testing it in Chrome?

**Comment by vbyjsue** [comment]
If I add breakpoint and check the network tabs, in chrome I get the correct json. In firefox it never completes the response since it gets the "Syntax.error..." in the "response-network-tab".

If I debug the handle_request method it has the response: "[400, {"Content-Type"=>"application/json"}, "{\"error\":{\"code\":5}}"]"

**Comment by ronwsmith** [comment]
Hmm, I am less familiar with the stubbing code.  Perhaps you need a `.to_json` after your hash?

**Comment by vbyjsue** [comment]
I've tried various formatting but the hash should be ok. As far as I can see the response is ok and it works in chrome. If I use cash persistance and replay it also works in firefox. Just curious to see if anyone else is having this problem. If it doesn't work in firefox it won't be usable to us and we really need these features.

**Comment by vbyjsue** [comment]
As I guessed I really need to learn more about ajax and http. The stub needed header Access-Control-Allow-Origin for the browser to accept the response. Works fine now.

**Comment by ronwsmith** [comment]
Thanks for reporting back!  Glad you got it working.
