### ISSUE TITLE
How can I load external Javascript from a <script> tag?

### ISSUE THREAD

**Issue by georgemillo** [oesmith/puffing-billy#104]
I'm trying to use puffing billy to test my interactions with Stripe, but it's not working.

You're not supposed to serve Stripe.js from your own server - it's only officially supported if you load it from `https://js.stripe.com/v2/`.

So I followed the instructions in [this tutorial](http://dev.contractual.ly/testing-stripe-js-with-mocked-network/) pretty much exactly, but when I run my tests, it looks like `stripe.js` isn't being loaded. I don't get a message explicitly telling me that the file can't be found - rather, my tests fail because . `ReferenceError: Can't find variable: Stripe`

Is puffing-billy failing to load stripe.js? Why? I don't even know where to begin in debugging.

Further information:

Rails 4.2.1
Rspec 3.1.7
Puffing Billy 0.5.0
Poltergeist 1.6.0

**Comment by georgemillo** [comment]
On further investigation, it seems that when I'm using `poltergeist` as my driver (as opposed to `poltergeist_billy`, stripe.js gets loaded fine.

Here are the only lines in my spec_helper which seem relevant to poltergesit and puffing billy:

    require 'capybara/poltergeist'

    Capybara.javascript_driver = :poltergeist

    RSpec.configure do |config|

      config.before(:each) do |example|
        if example.metadata[:js] || example.metadata[:billy]
          DatabaseCleaner.strategy = :truncation
        else
          DatabaseCleaner.strategy = :transaction
        end
        DatabaseCleaner.start
      end

      config.after do
        DatabaseCleaner.clean
      end

      config.before(:each, billy: true) do   
        Capybara.current_driver = :poltergeist_billy
      end

      config.after(:each, billy: true) do
        Capybara.use_default_driver
      end
    end

**Comment by ronwsmith** [comment]
What is your Billy.config?  Also, tail your logs and see if the cache is being hit?

**Comment by georgemillo** [comment]
Here's my `spec/support/billy.rb`. This is pretty much exactly what's given in the [tutorial](http://dev.contractual.ly/testing-stripe-js-with-mocked-network/) I linked above:

    require 'billy/rspec'

    Billy.configure do |c|
      c.cache = true
      c.persist_cache = true
      c.cache_path = 'spec/support/billy'
      c.non_whitelisted_requests_disabled = true
      # Stripe uses jsonp, which changes its callback param based on the current time
      # That means we'd never hit the cache, so this makes it ignore the param that changes
      c.dynamic_jsonp = true
      c.dynamic_jsonp_keys = ["callback"]
    end

Note that I'm using RSpec, but not Cucumber

**Comment by georgemillo** [comment]
Wait! I've just spotted this in my logs:

    puffing-billy: CACHE KEY for 'https://js.stripe.com:443/v2/' is 'get_js.stripe.com_1000b75c5f4169a090d304155dbe500ab29f907a'
    RuntimeError (puffing-billy: Connection to https://js.stripe.com:443/v2/ not cached and new http connections are disabled):

**Comment by georgemillo** [comment]
FINALLY got this to work by setting `non_whitelist_requests_disabled` to false.

I don't think the README is clear enough on what the "whitelist" actually means. I'm happy to edit it, just let me make sure I understand it correctly myself: if a URL is included in the whitelist, does this mean that  puffing billy WON'T try to cache requests to this URL?

**Comment by ronwsmith** [comment]
Whitelist means skipping the Billy proxy at all times.

The current description describes it pretty well: `c.non_whitelisted_requests_disabled is used to disable hitting new URLs when no cache file exists. Only whitelisted URLs (on non-blacklisted paths) are allowed, all others will throw an error with the URL attempted to be accessed.`

Feel free to modify it to make more sense to newcomers to the gem!

**Comment by georgemillo** [comment]
So if `non_whitelisted_requests_disabled` is true, does that mean that `whitelist` has no effect?

**Comment by ronwsmith** [comment]
Quite the opposite.  All requests except those in the `whitelist` will be disabled/blocked.

**Comment by georgemillo** [comment]
Oops, I meant to write "false" above.  Does `whitelist` have any effect if `non_whitelisted_requests_disabled` is false?

**Comment by ronwsmith** [comment]
Yes, whitelisted URLs bypass the cache:
https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/proxy_handler.rb#L91-92
