### ISSUE TITLE
Error loading HelloSign API iframe using poltergeist_billy

### ISSUE THREAD

**Issue by chrisjoywebb** [oesmith/puffing-billy#110]
I'm using the HelloSign API for a project and I'm running into an issue testing with puffing billy. The test passes normally when using the poltergeist driver for Capybara, but when using poltergeist_billy I get this error:

```
ReferenceError: Can't find variable: HelloSign
```

The test only fails when the proxy is set as follows when registering a Capybara driver in rails_helper.rb:
```
"--proxy=#{Billy.proxy.host}:#{Billy.proxy.port}"
```

It seems that the issue has to do with not loading the HelloSign iframe with the puffing billy server. Am I on the right path about that?

This is the test that I'm running (view [here](https://github.com/epicodus/epicenter/blob/test_not_passing_with_puffing_billy/spec/features/code_of_conduct_pages_spec.rb)):
```
feature 'viewing code of conduct document' do
  scenario 'as a student', js: true do
    student = FactoryGirl.create(:student)
    login_as(student, scope: :student)
    visit new_code_of_conduct_path
    within_frame('hsEmbeddedFrame') do
      expect(page).to have_content 'Sign to accept the Epicodus Code of Conduct'
    end
  end
end
```

This is the pertinent section of rails_helper.rb (view [here](https://github.com/epicodus/epicenter/blob/test_not_passing_with_puffing_billy/spec/rails_helper.rb#L17-L29)):
```
Capybara.register_driver :poltergeist_billy_custom do |app|
  options = {
    debug: true,
    extensions: ["http://s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"],
    phantomjs_options: [
      '--ignore-ssl-errors=yes',
      "--proxy=#{Billy.proxy.host}:#{Billy.proxy.port}",
    ]
  }
  Capybara::Poltergeist::Driver.new(app, options)
end

Capybara.javascript_driver = :poltergeist_billy_custom
```

And this is the view that is being rendered (view [here](https://github.com/epicodus/epicenter/blob/test_not_passing_with_puffing_billy/app/views/signatures/new.html.erb)):
```
<script type="text/javascript" src="//s3.amazonaws.com/cdn.hellofax.com/js/embedded.js"></script>
<script type="text/javascript">
    HelloSign.init('<%= ENV['HELLO_SIGN_CLIENT_ID'] %>');
    HelloSign.open({
        url: '<%= @sign_url %>',
        allowCancel: false,
        skipDomainVerification: true, // ONLY FOR TESTING
        messageListener: function(eventData) {
          if (eventData.event == HelloSign.EVENT_SIGNED) {
            document.location = "<%= url_for(controller: @controller_for_next_page, action: 'new') %>"
          }
        }
    });
</script>
```

The entire branch can be viewed [here](https://github.com/epicodus/epicenter/tree/test_not_passing_with_puffing_billy).

**Comment by ronwsmith** [comment]
That appears to be a JavaScript error.  Poltergeist fails by default for all JS errors.  You can disable with `js_errors: false` (I believe).

**Comment by ronwsmith** [comment]
@chrisjoywebb, is this still an issue for you?

**Comment by chrisjoywebb** [comment]
We were unable to solve the issue and decided to pass over these components of the integration tests. It had to do with loading times of the multi-layered iframe used by HelloSign, I presume.

**Comment by ronwsmith** [comment]
Closing -- stale issue.
