### ISSUE TITLE
Is there a way to use puffing-billy to return rack objects?

### ISSUE THREAD

**Issue by bytenel** [oesmith/puffing-billy#115]
So I have a Sinatra service faking a bunch of other things that I want to use to test my code. I don't want to have to start the service on my CI server, it'd be nice if I could just have my test route rack requests directly to an instance of that object. Hence where puffing-billy looks nice, I can return whatever I want from my requests it seems. Is it possible for puffing-billy to work similar to the stub_request #to_rack functionality in RSpec?

**Comment by ronwsmith** [comment]
No, it's not meant for that.

**Comment by ronwsmith** [comment]
@bytenel, I'm going to close this issue but please report back here if you find a workaround.
