### ISSUE TITLE
Is there a way to let proxy.stub() to match a regex pattern?

### ISSUE THREAD

**Issue by KingsleyZ** [oesmith/puffing-billy#116]
I am trying to match proxy.stub(/http:\/\/localhost:4567\/oauth\/authorize/) but it doesn't work. I am just wondering does stub support regex pattern? Thanks

**Comment by ronwsmith** [comment]
Looks like it should: https://github.com/oesmith/puffing-billy/blob/master/lib/billy/proxy_request_stub.rb#L57-L58

What are you seeing in the billy logs?

**Comment by ronwsmith** [comment]
@KingsleyZ, have you had a chance to check the logs?

**Comment by ronwsmith** [comment]
Closing -- stale issue.
