### ISSUE TITLE
Cannot make 2nd request to local app.

### ISSUE THREAD

**Issue by georgeu2000** [oesmith/puffing-billy#117]
I am using puffing-billy to mock external hosts.

The first request to my app works as expected:

    visit '/foo'

However, the second request shows:

    visit '/foo'

    The proxy server is refusing connections.

How to make more requests to the app?

It seems that puffing-billy is not supposed to intercept requests to the local app under test. Is this correct?

Using RSpec, Selenium and Firefox.

EDIT: It seems this is the same issue as https://github.com/oesmith/puffing-billy/issues/44, coming from WebMock. WebMock kills the proxy, but only after the first request.

I'll see if I can use puffing-billy for the app as well as the browser.

**Comment by ronwsmith** [comment]
Definitely a WebMock issue.  Please open an issue with that gem, if it doesn't exist already.

**Comment by ronwsmith** [comment]
Closing -- stale issue.  Also new workaround posted in https://github.com/oesmith/puffing-billy/issues/44#issuecomment-215888708
