### ISSUE TITLE
Hard dependency on eventmachine 1.0.4 downgrades me from 1.0.8

### ISSUE THREAD

**Issue by andrewfader** [oesmith/puffing-billy#120]
Can we do ~> 1.0.4?

**Comment by ronwsmith** [comment]
I attempted that at first but the test server used in the specs doesn't work with 1.0.8.

Mind taking a stab at fixing it?

**Comment by andrewfader** [comment]
The only errors I'm getting are "be_true" related in the proxy handler spec. Which were you seeing?

**Comment by ronwsmith** [comment]
Hmm, tried again and got the same errors as you.  Also merged a bunch of other PRs so I'm cutting a new gem from here: https://github.com/oesmith/puffing-billy/pull/123.

**Comment by ronwsmith** [comment]
@andrewfader, just pushed 0.6.1 with this change -- let me know if it works for you.

**Comment by andrewfader** [comment]
Great thanks!
