### ISSUE TITLE
Configuring webkit_billy

### ISSUE THREAD

**Issue by joshpfosi** [oesmith/puffing-billy#124]
I know there is a similar issue with poltergeist_billy. I am trying to pass the `allow_unknown_urls` to webkit using `webkit_billy`, however, registering my own driver as suggested in #61 only works for 1 example. For the next example, I continue to receive unknown url errors.

**Comment by rimian** [comment]
This should fix it:

https://github.com/oesmith/puffing-billy/pull/130

**Comment by ronwsmith** [comment]
Related PR has been released.  Closing issue.  Please report back if issue still exists.
