### ISSUE TITLE
release new version?

### ISSUE THREAD

**Issue by mcfiredrill** [oesmith/puffing-billy#132]
Hi,

Thank you for sharing this project. Its totally what I need.
I had various issues getting it to work in our app without using the latest git.
Perhaps because this commit is in HEAD:
https://github.com/oesmith/puffing-billy/commit/3c33fae4258726b5c7a613c791cc370f296ffc73

Would be great to see a new version of the gem released. :sweat_smile:

**Comment by ronwsmith** [comment]
Not sure I see the issue.  That commit says it's in 0.6.0 and 0.6.1 which have both been released.

**Comment by mcfiredrill** [comment]
My bad :(

iPhone$B$+$iAw?.(B

2015/11/12 12:12$B!"(Bronwsmith <notifications@github.com> $B$N%a%C%;!<%8(B:
