### ISSUE TITLE
PB not caching requests.

### ISSUE THREAD

**Issue by decareano** [oesmith/puffing-billy#138]
Hi, I am using `Puffing-billy` in a simple Rails app to play with it. I am unable to stubs calls. I am under the impression that if I run my feature with REAL api calls, I should get the stubbed call in the path I designated (ie: spec/req_cache/. My `test.log` shows `Proxy is listening on http://example.com:12345` but I don't see the cached request. Plus, I don't see the folder that is supposed to be created at  `spec/req_cache/.` Am I missing something? Thanks for the help.

https://github.com/decareano/doit_rails/commit/1e2c9603bf99578d080bc873e81d5f51a1ccc0b9

**Comment by ronwsmith** [comment]
You need to set the driver to `poltergeist_billy`

**Comment by decareano** [comment]
Hmmmm. I did. Same result. In my env.rb file I have:

Capybara.javascript_driver = :poltergeist_billy
Capybara.register_driver :poltergeist_billy do |app|
     Capybara::Poltergeist::Driver.new(app, :js_errors => false, :debug => true)
end
Sample code running a simple Cucumber feature: 

marcelo@marcelo-VirtualBox:~/doit_rails$ cucumber features/billy_sample.feature
Running via Spring preloader in process 4963
Using the default profile...
Feature: Stubbing via billy

  @javascript @billy
  Scenario: Test billy       # features/billy_sample.feature:4
{"id":"ebc388cc-3524-44fd-a12f-ebe7fb0f6d33","name":"set_js_errors","args":[false]}
{"command_id":"ebc388cc-3524-44fd-a12f-ebe7fb0f6d33","response":true}
{"id":"04cd019b-294e-401c-ac6b-a999c81ddd68","name":"set_debug","args":[true]}
{"command_id":"04cd019b-294e-401c-ac6b-a999c81ddd68","response":true}
{"id":"ea8ef079-7e85-4290-b6c0-b480b92be027","name":"visit","args":["http://www.yahoo.com/"]}
{"command_id":"ea8ef079-7e85-4290-b6c0-b480b92be027","response":{"status":"fail"}}

Note "fail" status in debug. Thanks for the help.

**Comment by ronwsmith** [comment]
Your `register_driver` line is overriding puffing-billy's defined driver.  Remove that and it should work.  If you need to preserve your js_errors and debug options, you'll need to start from the puffing-billy driver config here: https://github.com/oesmith/puffing-billy/blob/master/lib/billy.rb#L32-L40

**Comment by decareano** [comment]
I got rid of the block with `register_driver`. Now I only have: `Capybara.javascript_driver = :poltergeist_billy`. It should work except that now I am getting the timeout error: 
"Timed out waiting for response to {"id":"bc3ca91f-f6db-4888-b3ae-3f04ae45ae8f","name":"visit","args":["http://www.yahoo.com/"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)"

**Comment by ronwsmith** [comment]
Do you see anything being logged by puffing-billy?

**Comment by decareano** [comment]
Nope. No cached requests so far. 
Sample from Test.log: 
puffing-billy: Proxy listening on http://example.com:12345
  [1m[36m (0.5ms)[0m  [1mALTER TABLE "schema_migrations" DISABLE TRIGGER ALL[0m
  [1m[35m (3.1ms)[0m            SELECT schemaname || '.' || tablename
          FROM pg_tables
          WHERE
            tablename !~ '_prt_' AND
            tablename <> 'schema_migrations' AND
            schemaname = ANY (current_schemas(false))

  [1m[36m (2.6ms)[0m  [1mselect table_name from information_schema.views where table_schema = 'doit_rails_test'[0m
  [1m[35m (0.4ms)[0m  ALTER TABLE "schema_migrations" ENABLE TRIGGER ALL

Thanks for the help

**Comment by ronwsmith** [comment]
Are you using `:js` for the test you're running?

Looks like the branch on your repo doesn't include your latest changes.  Can you push up everything to review again?

**Comment by decareano** [comment]
yes, I am.
Feature: Stubbing via billy

@javascript @billy
Scenario: Test billy
   And a stub for a website

I will clean up my branch later. I want to figure out why is it that I cannot stub the request when I run the test. Thanks for the help.

**Comment by ronwsmith** [comment]
If you didn't change your `@billy` driver, you're still not using the correct one.

You need to update the driver within:
```ruby
Before('@billy') do
   Capybara.current_driver = :poltergeist
end
```

Not sure why you have two tags since they are only both used to set the driver.

**Comment by decareano** [comment]
Hope it helps. Look in the `features` folder.

https://github.com/decareano/doit_rails/tree/billy-only

thanks

**Comment by ronwsmith** [comment]
Any change in behavior after changing the driver used with `@billy` tags?  Looks fine to me.

**Comment by decareano** [comment]
No change in behavior. I am still puzzled as to why I cannot get the request to be stubbed. If, like you said, I use this: `Capybara.javascript_driver = :poltergeist_billy`
instead of this:
`Capybara.register_driver :poltergeist_billy do |app|`
`Capybara::Poltergeist::Driver.new(app, :js_errors => false, :debug => true)`
`end`
then we need to investigate the cause of the timeout. any way to insert a timeout hash options you can think of? I appreciate the help

**Comment by decareano** [comment]
I was able to generate the stubs using selenium driver. I' d rather use a headless browser but it's ok for now. 
When I run the stub for say, www.yahoo.com, it works fine `ONLINE` and `OFFLINE`. But when I run a scenario that stubs a local call to say, `http://127.0.0.1:xxxxxx`, if fails with an error: `Internal Server Error:  getaddrinfo: Name or service not known (SocketError)`. It looks to me that is more of an issue with my configuration than with the test. I was reading about this in Billy's README:  `By default, all requests to localhost or 127.0.0.1 will not be cached.`  I thought I had whitelisted with this: `c.whitelist = ['test.host', 'localhost' , '127.0.0.1']`. But it's not working. Can you help me with the configuration? FYI, the tests ALWAYS pass `ONLINE`. They failed `OFFLINE`.

**Comment by decareano** [comment]
Hi , I was wandering if I could get an opinion on my issue above. Thanks.

**Comment by ronwsmith** [comment]
Seems like you're unable to fetch the content the first time so there is nothing to cache.  `getaddrinfo: Name or service not known` indicates a DNS issue.

**Comment by ronwsmith** [comment]
Anything else we can help with @decareano or can this issue be closed?

**Comment by ronwsmith** [comment]
Stale issue
