### ISSUE TITLE
Gauging interest in config.after_cache_handles_request Proc

### ISSUE THREAD

**Issue by eliotsykes** [oesmith/puffing-billy#139]
If there's interest, would it be worthwhile adding a `after_cache_handles_request` configurable Proc to puffing-billy? If yes I can submit this monkey patch as a proper PR with tests:

```ruby
module Billy
  # puffing-billy/lib/billy/config.rb
  class Config
    attr_accessor :after_cache_handles_request
  end

  # puffing-billy/lib/billy/handlers/cache_handler.rb
  class CacheHandler
    def handle_request(method, url, headers, body)
      method = method.downcase
      if handles_request?(method, url, headers, body)
        if (response = cache.fetch(method, url, body))
          Billy.log(:info, "puffing-billy: CACHE #{method} for '#{url}'")

          if Billy.config.dynamic_jsonp
            replace_response_callback(response, url)
          end
          
          if Billy.config.after_cache_handles_request
            request = { method: method, url: url, headers: headers, body: body }
            Billy.config.after_cache_handles_request.call(request, response)
          end
          
          return response
        end
      end
      nil
    end
  end  
end
```
Source: https://github.com/eliotsykes/rspec-rails-examples/blob/1218eaa7ed64fb1660526f22b676d220b6ef4a6e/spec/support/puffing_billy.rb#L18-L47

Here's an example of it in use:
```ruby
Billy.configure do |c|
  ...
  fix_cors_header = proc do |_request, response|
    allowed_origins = response[:headers]['Access-Control-Allow-Origin']
    if allowed_origins.present?
      localhost_port_pattern = %r{(?<=http://127\.0\.0\.1:)(\d+)}
      allowed_origins.sub!(
        localhost_port_pattern, Capybara.current_session.server.port.to_s
      )
    end
  end
  c.after_cache_handles_request = fix_cors_header
  ...
end
```

This approach has been useful in that it means I don't need to continue to remember to edit any cached response files that have the `'Access-Control-Allow-Origin'` header after recording them. Previously, you'd need to remember to change the header in the cached file to a wildcard * value or to fix your Capybara.server_port so it never changes.

**Comment by sonjapeterson** [comment]
Was actually just thinking about submitting a PR for something like this because I'm having the same issue with CORs and random ports. I was thinking I'd add an option to do that Access-Control-Allow-Origin replacement specifically, but I like that this approach is more flexible.

**Comment by eliotsykes** [comment]
Good to know this would be useful for you too @sonjapeterson. 

I may not get round to this for some time unfortunately (I'd forgotten about this - thanks for the reminder). If you wanted it soon please feel free to take this contribution on.

**Comment by eliotsykes** [comment]
PS. @ronwsmith do you think this feature would be a welcome contribution?

**Comment by ronwsmith** [comment]
@eliotsykes any contribution that makes this gem useful to people is welcome (with tests!).

**Comment by sonjapeterson** [comment]
Cool, @eliotsykes I think I have some time to do this now so I'll go ahead with trying to put together a pr with tests for this

**Comment by ronwsmith** [comment]
PR #149 is close to merging, so I'll close this issue out.
