### ISSUE TITLE
filtering sensitive data a la VCR

### ISSUE THREAD

**Issue by tansaku** [oesmith/puffing-billy#143]
Hi Puffing Billy,

You're awesome, but do you have a way to filter sensitive data a la VCR?

https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/filter-sensitive-data

Many thanks in advance

**Comment by ronwsmith** [comment]
Not currently, no.  Original implementation was meant to cache non-sensitive data (such as pixels and other third-party content).  I know there are many users now caching stripe so it may make sense to add it.

Found the VCR code over here if someone wants to take a stab at it:
https://github.com/vcr/vcr/blob/ee289bd11f03fe35618e3f3b691a5b98a45981e7/lib/vcr/configuration.rb#L218-231

**Comment by ronwsmith** [comment]
@tansaku is still an issue you'd like to get resolved at some point?

**Comment by tansaku** [comment]
@ronwsmith yeah ...

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen if this is still desired.
