### ISSUE TITLE
cached responses should NOT include content-length

### ISSUE THREAD

**Issue by catmando** [oesmith/puffing-billy#144]
This is the problem behind #142 

Cached responses are including the Content-Length header, and if that value does not match the actual content length, then things break.

The actual content length may differ in the case of a jsonp request, where the callback id may not be the same number of characters as the value that was cached.

A quick monkey patch does the trick: 

```
# i.e add to spec_helper.rb
Billy::ProxyConnection.send(:define_method, :send_response) do |response|
  res = EM::DelegatedHttpResponse.new(self)
  res.status = response[:status]
  res.headers = response[:headers]
  res.headers.delete("Content-Length")
  res.content = response[:content]
  res.send_response
end
```

would you like a PR with this solution?

FYI I thought about simply not caching the Content-Length but that seems like a bad idea for a couple of reasons. 

1) This problem may exist in caches that are out there in the wild, and so the above solution works in spite of that.

2) It just feels better to write a the Content-Length if request_headers was asked for, and then blow it away when stubbing the request.

**Comment by ronwsmith** [comment]
I think the cleanest solution would be to not cache it when jsonp is enabled.  Please submit a PR deleting it conditionally over here: https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/proxy_handler.rb#L78

**Comment by ronwsmith** [comment]
@catmando I see that @jaydorsey made a monkey patch in his puffing-billy fork, but no PR was ever submitted.  If either of you submit a PR, I'd be happy to accept it.
