### ISSUE TITLE
is there a way to ignore params on everything rather than on just a few urls?

### ISSUE THREAD

**Issue by tansaku** [oesmith/puffing-billy#147]
for some services like google hangouts, disqus, stripe, etc. there are loads of urls that need to be added the ignore_params list - is there a way to just ignore params on everything, or possibly to just opt in a few urls for params?

**Comment by ronwsmith** [comment]
Not currently, no.  Perhaps we need to come up with a list of 'common' sites and default to those instead of nothing?

**Comment by tansaku** [comment]
or maybe a blacklist and whitelist for which URLs to ignore params on?

**Comment by puloms** [comment]
Is there a way to do this now? I mean, this issue is opened for a long time and I need to do something like a blacklist to just cache specific URLs.

**Comment by ronwsmith** [comment]
Feel free to submit a PR with your desired changes.

**Comment by puloms** [comment]
@ronwsmith a blacklist is fine? If so, I'll submit a PR when it's ready.

**Comment by ronwsmith** [comment]
How are you picturing the blacklist to work?  Would we only save params when the URL is in that list?

**Comment by ronwsmith** [comment]
@tansaku / @puloms is still a desired feature?

**Comment by tansaku** [comment]
@ronwsmith yep, would be handy thanks

**Comment by xtrasimplicity** [comment]
> Is there a way to do this now? I mean, this issue is opened for a long time and I need to do something like a blacklist to just cache specific URLs.

I've submitted a PR that _might_ help here: https://github.com/oesmith/puffing-billy/pull/279 :)

**Comment by ronwsmith** [comment]
@tansaku please try out the new feature in 2.3.0 from #279 and see if that meets your needs.

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen.
