### ISSUE TITLE
directories for different tests

### ISSUE THREAD

**Issue by tansaku** [oesmith/puffing-billy#152]
I'm working on testing multiple stripe payment options on our site, and I run into some problems in that the billy cache puts all the cache files in a single location shared by all tests, whereas VCR caches files in different directories depending on which test is running ... this means that tests for each different payment option use the same billy cache files, but then use different files for the server component, which causes an error: 

```
 You cannot use a Stripe token more than once (Stripe::InvalidRequestError)
```

I was wondering if there was anyway to have billy cache files for different tests in different directories?

Many thanks in advance

**Comment by ronwsmith** [comment]
Not currently built-in, no.  You can try changing the `cache_path` in a `before` block in your `rails_helper` and add the description to see if that works.

**Comment by tansaku** [comment]
thanks @ronwsmith - we appear to have got that working like so:

```rb
Before('@javascript') do |scenario, block|
  Billy.configure do |c|
    feature_name = scenario.feature.name.underscore
    scenario_name = scenario.name.underscore
    c.cache_path = "features/support/fixtures/req_cache/#{feature_name}/"
    Dir.mkdir(Billy.config.cache_path) unless File.exist?(Billy.config.cache_path)
    c.cache_path = "features/support/fixtures/req_cache/#{feature_name}/#{scenario_name}/"
  end
end
```

**Comment by ronwsmith** [comment]
@tansaku good to hear!  Feel free to create a PR to add that to the README.  I'll consider this issue closed.

**Comment by dmitry** [comment]
For test-unit could be used the following code:

```
module BillyHelper
  extend ActiveSupport::Concern

  included do
    setup :setup_billy
  end

  def setup_billy
    test_name = name.gsub(/[^a-z0-9\_]+/i, '_').gsub(/\A_+/, '')
    Billy.configure.cache_path = "test/billy_cache/#{test_name}/"
  end
end
```
