### ISSUE TITLE
Adding Watir support to Puffing Billy

### ISSUE THREAD

**Issue by mackermans** [oesmith/puffing-billy#157]
Hi @ronwsmith,

With my team I am currently integrating Puffing Billy into our Cucumber test suite, to allow the testing of user tracking events (therefore I needed to implement the request recording functionality). Unfortunately, since we are using Watir instead of Capybara, we are not able to use Puffing Billy as it is currently.

My question to you is if you are open to such a change, before we actually invest time. Maybe you have an idea on how this would be used?

I was thinking about having different entry points in projects that use puffing-billy, such as `require 'billy/capybara'` or `require 'billy/watir'`, along with the `require 'billy/cucumber'`  If the user doesn’t explicitly require Watir or Capybara, the default behavior would be to use Capybara. This way we ensure backwards compatibility. What do you think?

Best,

Maarten

**Comment by ronwsmith** [comment]
Hi @mackermans,

Personally, I would invest the time in getting off of Watir and onto Capybara.  It has much better community support and is more actively being developed.

If you want to continue down the Watir path, I don't think it will be too difficult if Wait supports similar driver initialization.  Take a look at [how the Capybara drivers are set up](https://github.com/oesmith/puffing-billy/blob/master/lib/billy.rb#L23-L70).  Puffing-billy is essentially a self-running proxy that Capybara sends traffic to.  You may just need to add in another `require` and a driver initialization section with your Watir config + proxy settings using `Billy.proxy`.

I can't think of another area that depends on Capybara, so fingers crossed, that will do it!

**Comment by mackermans** [comment]
Unfortunately, it would be an insane amount of work to rewrite our tests to work with Capybara. So we have no other choice but to go with Watir. See PR https://github.com/oesmith/puffing-billy/issues/158

**Comment by mackermans** [comment]
@ronwsmith Could you take a look at the PR (#158)? If you agree I can start writing the documentation, after which we can merge.

**Comment by ronwsmith** [comment]
Will close the issue as we can wrap things up in the PR.
