### ISSUE TITLE
EventMachine 1.1.4 breaks certain puffing-billy requests

### ISSUE THREAD

**Issue by asafbrukarz** [oesmith/puffing-billy#164]
A change made to the default request compressing in `em-http-request` (https://github.com/igrigorik/em-http-request/commit/8c72228d7cf29cba1c72745d6fd0fcc2ab45a8bb) has broken certain puffing billy requests for us.

This took a long time to diagnose, but when requests are made to load Google maps from the client, `//maps.googleapis.com/maps/api/js?v=3.exp&callback=...` the proxy returns a 0 length response.

Locking `em-http-request` to `1.1.3` fixes this issue. Any thoughts?

**Comment by ronwsmith** [comment]
Let's pin the version for now until someone has time to investigate further.  Can you PR that?

**Comment by damned** [comment]
just issued a pull request to a potential fix for this: #167

build seems to work against em-http-request

**Comment by ronwsmith** [comment]
@asafbrukarz does the PR from @damned fix the issue you were seeing?

**Comment by ronwsmith** [comment]
@asafbrukarz any update here?

**Comment by AlanFoster** [comment]
We're hitting unexpected errors, potentially related to this issue. Any updates would be good :+1:

**Comment by ronwsmith** [comment]
@AlanFoster can you try the fix in this PR: https://github.com/oesmith/puffing-billy/pull/167  If it works, I'll get it merged in soon.

**Comment by rogerkk** [comment]
I'm sorry if this is not the best place to post this question, but I'm struggling with getting puffing-billy installed and stumbled upon this issue. Perhaps any answer to my question can help someone else with the same issue:

The puffing-billy master branch (and the 0.9.2 gem) seems to be [pinned to eventmachine ~> 1.0.4](https://github.com/oesmith/puffing-billy/blob/master/Gemfile.lock#L8), but I have other gems depending on a more recent version of eventmachine.

This issue mentions eventmachine 1.1.4, but could someone help me understand how I even get to install puffing-billy with that (or more recent) versions of eventmachine?

**Comment by ronwsmith** [comment]
@rogerkk try using the branch from PR #167 and see if that works for you.

**Comment by jurglic** [comment]
@ronwsmith Any idea when #167 can be merged? I have similar issue with billy as @rogerkk, have other gems depending on newer version of eventmachine...

**Comment by ronwsmith** [comment]
@jurglic have you tried using that branch to verify it works before I merge it?

**Comment by jurglic** [comment]
@ronwsmith  Yes I'm using this branch. Additionally I've bumped addressable to `2.5.0` and eventmachine to `1.2.3`  (bb875294).

All works for me.

**Comment by ronwsmith** [comment]
@jurglic Great, thanks for verifying!  Can you create a PR with those two updated gems and this change?

**Comment by jurglic** [comment]
Sure, will do

**Comment by ronwsmith** [comment]
I lot has changed around gems since this PR was opened.

Are people still having the same issues using 0.12.0?

**Comment by dmitry** [comment]
Probably a good idea would be to close this issue, as it seems eventmachine was updated to a lot newer version, so it might be solved.

**Comment by ronwsmith** [comment]
Feel free to reopen if anything comes up

**Comment by dreyks** [comment]
Um... so, what's the current state with EM compatibility? My code already uses EM at `1.2.3` so I can't install puffing-billy which is still at `~> 1.0.4`
https://github.com/oesmith/puffing-billy/commit/bb8752940c43cb7ccd2f13a511131ebfffa5cdaa seems not to exist in any  branch anymore

**Comment by dreyks** [comment]
More info

It seems like first the em version was pinned to `~> 1.0.4` by https://github.com/oesmith/puffing-billy/pull/206 because something was breaking with em > 1.0.9.1
But in several months the requirement was pinned to `1.2.0.1` in https://github.com/oesmith/puffing-billy/pull/217 by same person @mwjeffcott 
The question is Why would we pin it then if it's already past 1.0.9.1?

Also https://github.com/oesmith/puffing-billy/pull/212 pins em version back to `~> 1.0.4` presumably because of watir [more info](https://github.com/oesmith/puffing-billy/pull/212/files#diff-752c3d3303256b2b755956cf77df54edR33)
