### ISSUE TITLE
How to whitelist a domain for an embed script e.g. soundcloud

### ISSUE THREAD

**Issue by StevenIseki** [oesmith/puffing-billy#179]
We have a custom audio player using the soundcloud API, and we are using puffing-billy to proxy calls to the soundcloud API in rspec. It works like this and works nicely.

```
  background do
    proxy.stub(
      "https://api.soundcloud.com:443/tracks/#{audio&.soundcloud_id}/stream"
    ).and_return(body: fixture_file('audio.mp3'), content_type: 'audio/mpeg')
  end
```

Due to the number of play limit using the soundcloud API we have to use another approach, controlling a soundcloud player embed script with our custom player as shown [here](https://developers.soundcloud.com/docs/api/html5-widget#playground).

In our tests, we need to whitelist the `https://w.soundcloud.com` domain, and presumed we could add the `whitelist` option and update our config to the following:

```
Billy.configure do |c|
  c.cache = true
  c.persist_cache = true
  c.non_whitelisted_requests_disabled = false
  c.whitelist = ['https://w.soundcloud.com/player']
end
```

However this doesn't seem to work. I am just trying to whitelist the url in the iframe src so the soundcloud embed player works on the page:

```
<iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/333333%3Fsecret_token%3Ds-z5ofy"></iframe>
```

**Comment by ronwsmith** [comment]
So you want to bypass puffing-billy for `https://w.soundcloud.com`?  Have you tried whitelist with just `w.soundcloud.com`  What do you see in the logs?
