### ISSUE TITLE
Control cache yml name

### ISSUE THREAD

**Issue by queso** [oesmith/puffing-billy#18]
VCR let's you control and decide the cassette name for each test if you want - do you guys feel this would be desirable for the persistent cache setup in puffing-billy?

The reason I ask is that I am making four calls to Stripe and it caches the first one and doesn't understand the next three are separate tests with new data, so they fail when they replay the wrong interaction.

**Comment by ronwsmith** [comment]
Scoping will resolve this issue.  Closing.
