### ISSUE TITLE
Remote Webdriver puffing billy?

### ISSUE THREAD

**Issue by RubyGemTSL** [oesmith/puffing-billy#180]
Hi,

Apologies if this is not the correct domain to raise this question.

Our CI server runs on remote machines, and test are executed using remote webdriver. 

My question is, is possible to record stubbed data locally and then when running tests using remote webdriver use this stubbed data? 

I tried to modify my remote chrome browser to include the Billy proxy server without success:

```
def docker_chrome

    chrome_switches = %W[--proxy-server=#{Billy.proxy.host}:#{Billy.proxy.port} --ignore-certificate-errors --disable-popup-blocking --incognito]
    caps_opts = {'chrome.switches' => chrome_switches}

    caps = Selenium::WebDriver::Remote::Capabilities.chrome(caps_opts)
    caps['chromeOptions'] = {'prefs' => chrome_prefs}

    Watir::Browser.new(
        :remote,
        :url => 'http://192.168.99.100:4444/wd/hub',
        :desired_capabilities => caps
    )

  end


```

Thanks,
Ian

**Comment by ronwsmith** [comment]
I saw this issue before you added your config and that's exactly how I was going to suggest trying it.  I'm guessing it doesn't work because the remote machine doesn't route back to your local machine to hit the puffing-billy proxy.

**Comment by RubyGemTSL** [comment]
@ronwsmith yes that's what I thought. I'm sure there must be a way around this. I'll keep trying.

**Comment by RubyGemTSL** [comment]
Hi @ronwsmith,

I have recently came back to this and still having issues. 

I have configured the cocker chome browser like:

```
def docker_chrome

  puts "Proxy server should have been listening on: #{Socket.ip_address_list[1].ip_address}:80}"
      chrome_switches = %W[--proxy-server=#{Socket.ip_address_list[1].ip_address}:80 --ignore-certificate-errors --disable-popup-blocking --incognito]
        caps_opts = {'chrome.switches' => chrome_switches}

    caps = Selenium::WebDriver::Remote::Capabilities.chrome(caps_opts)
    caps['chromeOptions'] = {'prefs' => chrome_prefs}

    Watir::Browser.new(
        :remote,
        :url => 'http://192.168.99.100:4444/wd/hub',
        :desired_capabilities => caps
    )

  end

```

The problem is I have is Puffing Billy is listening on puffing-billy: http://localhost:43372 when I want it to listening on: 192.168.192.5:80

Can you see what I am doing wrong here?

**Comment by RubyGemTSL** [comment]
Actually it doesn't seem to just be within docker. I also have the same issue with local chrome. For example:

```
def chrome(device_name = nil)
    chrome_switches = %W[--proxy-server=#{Billy.proxy.host}:#{Billy.proxy.port} --ignore-certificate-errors --disable-popup-blocking]
    caps_opts = { 'chrome.switches' => chrome_switches }
      caps = Selenium::WebDriver::Remote::Capabilities.chrome(caps_opts)
      Watir::Browser.new(:chrome, desired_capabilities: caps)
  end

```

And the test scenario:

Given(/^I navigate to the homepage/) do
  proxy.stub('http://www.google.com/').and_return(:text => "I'm not Google!")
  @browser.goto('http://www.google.com/')
end

Then(/^I should see "([^"]*)"$/) do |text|
  expect(@browser.html).to include(text)
end

```

The call to google.com is not stubbed :/

Is there a problem with the way I am creating the driver?

**Comment by RubyGemTSL** [comment]
OK apologies, local chrome needs to be configured differently and works fine with the below config:

```
  def chrome
    chrome_switches = %W[--proxy-server=#{Billy.proxy.host}:#{Billy.proxy.port} --ignore-certificate-errors --disable-popup-blocking]
    Watir::Browser.new(:chrome, switches: chrome_switches)
  end
```

Remote Watir doesn't use the switches option so it is back to the issue of not stubbing for remote browsers :-/

**Comment by RubyGemTSL** [comment]
I've also tried the following hook:
```
Billy.configure do |c|
  c.proxy_host = '0.0.0.0' # also tried http://0.0.0.0, and Socket.ip_address_list[1].ip_address (docker ip address)
  c.proxy_port = 80
end
```
Result of the above puffing billy always listens on localhost and random port.
```
I, [2016-12-15T21:34:38.933260 #28]  INFO -- : puffing-billy: Proxy listening on http://localhost:38445
```
Maybe I am misunderstanding the config options but the above hook should request puffing billy to listen on that host and port?

**Comment by ronwsmith** [comment]
You're interpreting it correctly -- where is your Billy config block?  What else is in it?

Any particular reason you're not using `Billy::Browsers::Watir.new`?

**Comment by RubyGemTSL** [comment]
Hi @ronwsmith 

I now have puffing-billy listening on the correct host and port using the following config:

```
Billy.configure do |c|
  c.non_whitelisted_requests_disabled = false
  c.cache = true
  c.non_successful_cache_disabled = true
  c.persist_cache = true
  c.strip_query_params = false
  c.record_stub_requests = true
  c.proxy_host = Socket.ip_address_list[1].ip_address
  c.proxy_port = 10000
  c.cache_path = '_cucumber/billy_cache'
  FileUtils.mkdir_p(Billy.config.cache_path) unless File.exist?(Billy.config.cache_path)
end

Billy.proxy.reset_cache
Billy.proxy.start
```

By adding the following puffing-billy attempts to listen on the desired host and port.
```
Billy.proxy.reset_cache
Billy.proxy.start
```

The problem I have is the test is still not being stubbed.

I cannot use `Billy::Browsers::Watir.new?` because it thrown an error as I am running tests in docker I need to use a remote browser, hence my browser definition:

```
def docker_chrome(device_name = nil)
    stubbed = ENV['STUBBED_DATA'] || 'true'
    if stubbed == 'true'
      $stubbed = true
      chrome_switches = %W(--proxy-server=http://#{Billy.proxy.host}:#{Billy.proxy.port} --ignore-certificate-errors --disable-popup-blocking)
    else
      chrome_switches = %w(--ignore-certificate-errors --disable-popup-blocking --incognito)
    end

    caps_opts = { 'chrome.switches' => chrome_switches }
      caps = Selenium::WebDriver::Remote::Capabilities.chrome(caps_opts)
      caps['chromeOptions'] = { 'prefs' => chrome_prefs } 
    client = Selenium::WebDriver::Remote::Http::Default.new
    client.timeout = 300 # Browser launch can take a while

    begin
      attempts = 0
      Watir::Browser.new(:remote, url: ENV['SELENIUM_HOST'], desired_capabilities: caps, http_client: client)
    rescue Net::ReadTimeout => e
      if attempts == 0
        attempts += 1
        retry
      else
        raise(e)
      end
    end
  end

```

**Comment by ELepolt** [comment]
@ianrhamilton, did your setup above actually end up working? Nearing 4 years later and I've run into this same issue.
