### ISSUE TITLE
How to regenerate persistent cache?

### ISSUE THREAD

**Issue by pacaplan** [oesmith/puffing-billy#191]
Is there configuration setting in order to bypass the cache read, issue the request, and persist the new response, overwriting any existing cache file? I.e., what {record: :all} does for VCR?

I am using with rspec and VCR, and a large number of specs. The cache directory is quite large, and it is not straightforward to determine which cache files correspond to which spec. Right now, I am unable to find a way to regenerate the persistent cache for a single spec, without deleting the entire cache directory, and regenerating for all.

**Comment by ronwsmith** [comment]
No, because by default everything is based on the (primarily) external URLs and the keys are spec-agnostic.

If you'd like to separate your puffing-billy cache by spec, check out this section of the readme:
https://github.com/oesmith/puffing-billy#separate-cache-directory-for-each-test-in-cucumber

**Comment by pacaplan** [comment]
Ok, thank you. I presume something like that would work in an rspec before block as well?

**Comment by ronwsmith** [comment]
Yes, definitely.

**Comment by ronwsmith** [comment]
Workaround above, closing.
