### ISSUE TITLE
Can I use the request header in the stubbed response?

### ISSUE THREAD

**Issue by joshweir** [oesmith/puffing-billy#192]
Is it possible to use the request header in the stubbed response, I suppose like this?:

    proxy.stub('http://www.google.com/').and_return(:text => request.header.inspect)

I'd like to test the request headers.

**Comment by ronwsmith** [comment]
That would put the request headers in the response body.  If you want the same [headers](https://github.com/oesmith/puffing-billy/blob/master/lib/billy/proxy_request_stub.rb#L31) back in the response headers, try `:headers => foo`.
