### ISSUE TITLE
Provide an API for accessing the list of proxied requests that were not stubbed

### ISSUE THREAD

**Issue by AlanFoster** [oesmith/puffing-billy#195]
Hey,

I've been using puffing billy for a while now, and it's really great. I was thinking we could expand the API to additionally expose how many requests had to be proxied, as they weren't stubbed.

In my particular use case, it turned out that a CORS request wasn't properly mocked and reached out to the real service. This meant that sometimes our tests passed, but would be flakey. From visual inspection it seemed as though the requests were mocked correctly, but it turned out to not be the case.

It would have been nice to add an additional assertion as part of our rspec capybara tests to ensure that nothing's made through unexpectedly:

```ruby
after :each do
  expect(proxy.proxied_requests).to be_empty
end
```

This would be nice as it would highlight any unexpected values getting through without realising it, and allow for developers to see the exact request paths that they _should_ mock, i.e. sometimes we've forgotten to add the port `:443` to the stubbed path for HTTPS requests - and this sort of assertion would immediately highlight the issue to the developer.

I'm happy to add this functionality to puffing billy, however I'm not sure if the threading model of the underlying event machine. i.e. is a naive solution of appending each proxied request to simple list of requests enough, or will I need to introduce mutexes etc to ensure there's no possible race conditions?

**Comment by ronwsmith** [comment]
There should be logging when real requests are going through.  Perhaps you can monitor or capture the logs in the interim?  I personally turn off the internet and see if anything breaks.
