### ISSUE TITLE
Puffing-billy doesn't work with https urls 

### ISSUE THREAD

**Issue by dastanko** [oesmith/puffing-billy#201]
Sample testing code for stubbing github api requests.

```ruby 
ENV["RAILS_ENV"] ||= 'test'

require File.expand_path("../../../config/environment", __FILE__)
require 'rspec/core'
require 'rspec/rails'
require 'capybara/rspec'
require 'billy/capybara/rspec'

require 'rack/utils'

Capybara.app = Rack::ShowExceptions.new(Sample::Application)

Capybara.configure do |config|
  config.default_driver = :webkit_billy
  config.default_max_wait_time = 10
end

Capybara::Screenshot.register_driver(:webkit_billy) do |driver, path|
  driver.save_screenshot(path)
end

Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
end

RSpec.configure do |config|
  config.include Capybara::DSL
end

describe 'Actions' do

  it 'shows index page' do
    url = 'https://api.github.com/'
    file = File.read('./github.json')
    hash = JSON.parse(file)
    proxy.stub(url).and_return(json: hash)

    visit '/actions/index'
    sleep 20
    screenshot_and_open_image
    expect(page).to have_content('abcdefghi')
  end
end
```
in index.html.erb:
```html
<h1>Actions#index</h1>
<p>Find me in app/views/actions/index.html.erb</p>

<script>
    $(function () {
        $.get("https://api.github.com/", function (item) {
            $("h1").text(item.current_user_url);
        })
    });
</script>
```
in github.json I have:
```javascript
{
  "current_user_url": "abcdefghi"
}
```

And it's not stubbing https url. The browser does real requests on server by https.

Gem versions:
```
capybara (2.13.0)
capybara-webkit (1.14.0)
puffing-billy (0.10.1)
```

**Comment by ronwsmith** [comment]
Thanks for the detailed write-up!

Does it work with just `http` and the same config?  Have you tried other drivers?

**Comment by dastanko** [comment]
I tried sample code with google example on main page, which worked fine. I've tried poltergeist, I think it has the same problem.

**Comment by ronwsmith** [comment]
Could it be another CORS issue (from your other issue)?  Does it not work for any base domains?

**Comment by dastanko** [comment]
I think it is not related to CORS problem. 
I've tried several domains, result was the same.

**Comment by dastanko** [comment]
I've tried solution suggested in https://github.com/oesmith/puffing-billy/issues/202#issuecomment-343344868. And it works just for http requests. The problem remains for https requests.

**Comment by Jack12816** [comment]
@dastanko AFAIK Webkit/Blink/Chrome require valid certificates or they need to be configured explicitly to ignore SSL errors. In your case capybara-webkit [can be configured](https://github.com/thoughtbot/capybara-webkit#configuration) to ignore SSL issues like this:

```ruby
Capybara::Webkit.configure do |config|
  # Don't raise errors when SSL certificates can't be validated
  config.ignore_ssl_errors
end
```

You could also take care of importing the new puffing billy certificate authority if you find out how to do it on capybara-webkit. Then every HTTPS request is valid and secure.

**Comment by dastanko** [comment]
I've checked out the `ignore_ssl_errors` solution and it doesn't work.

**Comment by dastanko** [comment]
Thanks @AlanFoster for the clue. Now it works even without `ignore_ssl_errors` conifg. However, I don't quite understand why the port should in url when you are stubbing https. Ok, whatsever.

By the way was also a problem with trailing backslash, if I drop it out, the stub doesn't work. It can be real issue, it was a trick in which I was trapped. So it would be good to have this problem fixed.

**Comment by AlanFoster** [comment]
@dastanko It works without your explicit `ignore_ssl_errors` config, because I believe puffing billy has that configuration by default:

https://github.com/oesmith/puffing-billy/blob/master/lib/billy/browsers/capybara.rb#L37-L45

I had created a ticket to add some useful analytics https://github.com/oesmith/puffing-billy/issues/195 - which would help give some visibility in this sort of scenario, but I'm still unsure about exactly what analytics and methods I'd want puffing billy to provide still 💭

**Comment by AlanFoster** [comment]
@dastanko As a concrete example:

```ruby
  def stub_github
    github_url = 'https://api.github.com:443/'
    proxy.stub(github_url).and_return({
      headers: {
        'Access-Control-Allow-Methods' => 'GET, PATCH, POST, PUT, OPTIONS',
        'Access-Control-Allow-Origin' => '*'
      },
      json: {
        mock_server_response: true,
        current_user_url: 'https://api.github.com/user'
      }
    })
  end

  before(:each) do
    stub_github

    ...
  end
```
