### ISSUE TITLE
How can I tell if the stub is getting hit?

### ISSUE THREAD

**Issue by hackmastera** [oesmith/puffing-billy#210]
Is there some indication in the log? Thanks.

**Comment by ronwsmith** [comment]
Should be pretty clear in the logs:
https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/stub_handler.rb#L14

**Comment by hackmastera** [comment]
Thanks! I was hoping to see something like that. I guess I never got it working right. appreciate the follow-up.
