### ISSUE TITLE
Websockets issue

### ISSUE THREAD

**Issue by lpender** [oesmith/puffing-billy#214]
I see the following when I try to use `chrome_billy` or `selenium_billy` with SockJS

![image](https://user-images.githubusercontent.com/1406554/35336932-73c5f01c-014c-11e8-940e-32def6d9cff2.png)

The problem doesn't exist if I just use `:chrome` as the browser.

**Comment by ronwsmith** [comment]
I'm not familiar with SockJS -- do you see anything in the logs when this occurs?  What are you expecting to happen?

**Comment by lpender** [comment]
SockJS is bundled with i.e. [webpack-dev-server](https://github.com/webpack/webpack-dev-server) and is used for instant reloading. I'm expecting it to connect normally, as it does in chrome.

Trying to think of how I could come up with a minimal test case...

**Comment by lpender** [comment]
Here is a site that shows the behavior perfectly:

https://www.meteor.com/showcase

in Rspec:

```
visit "https://www.meteor.com/showcase"
```

**Comment by ronwsmith** [comment]
Related PR closed, closing issue.
