### ISSUE TITLE
Puffing billy conflict with  javascript AddEventlistener

### ISSUE THREAD

**Issue by misner** [oesmith/puffing-billy#215]
I know the two should be totally unrelated but here is a description of the phenomenon my rspec test is experiencing.

I am using rspec 3, capybara, webkit-capybara driver.

At first I thought that the issue was related to puffing billy not catching request (https://github.com/oesmith/puffing-billy/issues/213) but in fact as I have a quite javascript-heavy app, I tried to check if the issue was not that Puffing billy was not playing well with my javascript.

Her's is the gist of the experiment/bug-tracking-down and some seemingly super weird conclusions:

**spec_helper.rb**

```
# Configuration of Capybara
  # must be set  before database cleaner configuration is defined. 
  Capybara.javascript_driver = :webkit # source https://github.com/jnicklas/capybara#using-capybara-with-rspec
  # Custom config of Capybara when use puffing billy
  config.before(:each, billy: true) do
    Capybara.current_driver     = :webkit_billy
    Capybara.javascript_driver  = :webkit_billy    
  end
  # go back to standard drivers when not running puffing billy-involved tests
  # reason: some tests involving capybara webkit features (ex: resize_window
  # are not supported by webkit_billy)
  config.after(:each, billy: true) do
    Capybara.current_driver     = :webkit
    Capybara.javascript_driver  = :webkit
  end

Capybara.configure do |config|
    # we must force the value of the capybara server port. We have to do that because puffing-billy
    # saves everything locally for a specific host and port. But, capybara starts your rack application
    # on a new port each time you run your tests. The consequence is puffing-billy
    # is not able to reuse the created cache files and tries to do all the API call again.
    # source - kevin.disneur.me/archives/2015-03-05-end-to-end-tests-in-javascript.html
    config.server_port = 60001
    # source: comments in coderwall.com/p/jsutlq, enable to load save_and_open page with css and js
    config.asset_host  = 'http://localhost:3000'
  end

require 'billy/capybara/rspec'
Billy.configure do |c|
  c.cache = true
  c.cache_request_headers = false
  c.persist_cache = true
  # used to NOT cache responses like 500, 404, i.e reponses without 200-series or 304 status codes.
  # This prevents unauthorized or internal server errors from being cached and used for future test runs.
  c.non_successful_cache_disabled = true
  c.non_successful_error_level = :warn
  c.whitelist = [ 'localhost',
                  '127.0.0.1',
                  'https://res.cloudinary.com:443', 
                  'https://d2vsjqr9p2w23h.cloudfront.net:443',
                  'https://cdnjs.cloudflare.com:443']
  c.ignore_cache_port = true
  c.cache_path = "spec/support/http_cache/billy/"    
  c.non_whitelisted_requests_disabled = true 
end
```

**rspec_test.rb**

```
context "On a page", js: true, billy: true do
   describe "Spinner on the Page load", js: true do				
	   it "works fine", js: true do	
              visit deal_page_path(deal)
             save_and_open_page
     end
  end
end

```

**Here is my javascript:**

```
var BackdImg       = document.getElementById('introImgHolder');
  
if (BackdImg.addEventListener) {
    //For all major browsers, except IE 8 and earlier
    BackdImg.addEventListener('load', actionsTriggeredAfterBackgImgLoad);
  } else if (BackdImg.attachEvent)  {
    //For IE 8 and earlier versions
    BackdImg.attachEvent('load', actionsTriggeredAfterBackgImgLoad);
  }
  
  function actionsTriggeredAfterBackgImgLoad() {
    loadIntroScreen();
    BackdImg.removeEventListener('load', actionsTriggeredAfterBackgImgLoad);//detach load to prevent infinite cycle
  }
```

I had suspicions that actionsTriggeredAfterBackgImgLoad() was not being executed and was the reason for my initial [ticket](https://github.com/oesmith/puffing-billy/issues/213). I used a little trick and placed a simple but very visual change on the page then using save_and_open_page (see rspec code above) to see if i can see it in practice on my browser.

So I added` $(".navbar-brand").css("color","red")` at different places in the following experiments to see when I could see it in front of me on my browser thanks to save_and_open_page.

**Experiment 1: billy: true is not present at all = not using puffing billy**
save_and_open_page opens the deal page and the logo is has turned form black to red. It was to be expected. 

**Experiment 2: now using billy: true, and placing the css change INSIDE  function actionsTriggeredAfterBackgImgLoad()** like below:

```
 function actionsTriggeredAfterBackgImgLoad() {
     $(".navbar-brand").css("color","red") ;
    loadIntroScreen();
    BackdImg.removeEventListener('load', actionsTriggeredAfterBackgImgLoad);//detach load to prevent infinite cycle
  }
```

save_and_open_page opens the deal page and the logo is still black. It has not become red!
It means with puffing billy "on", **the content of the function actionsTriggeredAfterBackgImgLoad is not being executed.**

Now things are about to get really weird.

**Experiment 3: still using billy: true, but this time placing the css change directly inside the  BackdImg.addEventListener line**

```
if (BackdImg.addEventListener) {
    //For all major browsers, except IE 8 and earlier
    BackdImg.addEventListener( 'load', $(".navbar-brand").css("color","red")  );
  } else if (BackdImg.attachEvent)  {
    //For IE 8 and earlier versions
    BackdImg.attachEvent( 'load', $(".navbar-brand").css("color","red")  );
  }
```

Outcome: the logo changed from black to red !!!
To be honest I did this last experiment just to fiddle around and try as many places as possible for the css color change code  and did not expect this outcome. I was so surprised that I repeated those 2 last experiments multiples times to be sure and it keeps giving me the same result.
This means that for some super weird reason, when puffing billy is "on", the function actionsTriggeredAfterBackgImgLoad() is not working when it's "mentioned/referred to" inside this javascript addEventlistener . This would totally explain my initial bug described on https://github.com/oesmith/puffing-billy/issues/213

This is beyond my understanding and abilities to be honest. Is it possible webkit_billy has issues with the javascript addEventlistener ?

Any guess on what's happening ?

**Comment by twalpole** [comment]
I don't think the results you're seeing are implying what you think they are.  Your `Experiment 3` is doing what it's doing because you're not actually attaching the code as an event handler, rather it's immediately running the code `$(".navbar-brand").css("color","red")` and attaching the result of that as an event handler.  For it to be attached as an event handler you'd need something like

    BackdImg.addEventListener( 'load', function(){ $(".navbar-brand").css("color","red") } );

Instead what I think you're seeing is that when using Billy with cached resources the `load` event is firing before you actually attach your listener. You might want to check whether `document.readyState` already equals 'complete' before attaching your event listener.

**Comment by misner** [comment]
Could using turbolinks and jquery.turbolinks gem have an impact on what you just mentionned (" using Billy with cached resources the load event is firing before you actually attach your listener, due to the speed responses come. You might want to check whether document.readyState already equals 'complete' before attaching your event listener.") ?

**Comment by twalpole** [comment]
@misner Using turbolinks changes everything because there would only be a `load` event on the initial page load, not for any that turbolinks makes.   `jquery.turbolinks` is obsolete (https://github.com/kossnocorp/jquery.turbolinks) and doesn't work with the latest turbolinks (5+), but if you're using it with legacy turbolinks then I believe you'd want to use the `page:load` event it emits instead of 'load'.  If rewriting your code to not use `jquery.turbolinks` and just using the latest turbolinks then I believe the event you want would be `turbolinks:load `

**Comment by misner** [comment]
Thanks will move forward and update. Yes still using Turbolinks Classic.

**Comment by misner** [comment]
Finally understood the issue and posting it here as it does relate to Puffing Billy use and might help other people facing a similar issue:

To sum it up, when not using puffing billy,  actionsTriggeredAfterBackgImgLoad() below is executed, and when using billy: true and with cached "on", it was not.

if (BackdImg.addEventListener) {
    //For all major browsers, except IE 8 and earlier
    BackdImg.addEventListener('load', actionsTriggeredAfterBackgImgLoad);
  } else if (BackdImg.attachEvent)  {
    //For IE 8 and earlier versions
    BackdImg.attachEvent('load', actionsTriggeredAfterBackgImgLoad);
  }
  
  function actionsTriggeredAfterBackgImgLoad() {
    loadIntroScreen();
  }

What triggered me to undesrtand the problem was this code:

**Comment by twalpole** [comment]
@misner Ah - I should have read the variable name - I had assumed the document load event -  
 element load event would not be affected by turbolinks (unless restoring from turbolinks cache) - glad you worked it out. Although, why a 304 (not modified) would be considered an error is questionable, since that shouldn't be returned unless the "browser" has the item in its cache already and has sent an `If-Modified-Since` header (or Etag, etc).  In that case it is the browsers responsibility to just render the image from its cache - not really an error.

**Comment by ronwsmith** [comment]
@misner we good to close this issue?

**Comment by misner** [comment]
yes we are. thanks.
