### ISSUE TITLE
Stack Trace in cache lookup

### ISSUE THREAD

**Issue by v-w** [oesmith/puffing-billy#22]
I get the following stack trace...

The http parser returns the uri part, so the cache code get a null when it tries to construct the full url path.
@header_data in proxy connection shows this:
GET /v1/someobjects?id=1b0d1735-96ba-4d8f-9da7-71e03f5e5fbe HTTP/1.1\r\nHost: 10.0.0.2:9999\r\nConnection: keep-alive\r\nAccept: */*\r\nUser-Agent: BLAH/1.0\r\n\r\n"

Stack Trace seen:

NoMethodError
undefined method `+' for nil:NilClass
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/puffing-billy-0.2.1/lib/billy/cache.rb:74:in `key'
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/puffing-billy-0.2.1/lib/billy/cache.rb:21:in `cached?'
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/puffing-billy-0.2.1/lib/billy/proxy_connection.rb:83:in `handle_request'
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/puffing-billy-0.2.1/lib/billy/proxy_connection.rb:55:in `on_message_complete'
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
/Users/someuser/.rvm/gems/ruby-1.9.3-p392/gems/puffing-billy-0.2.1/lib/billy/proxy.rb:68:in `main_loop'

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to re-open with additional details.
