### ISSUE TITLE
Response is being truncated when it includes multibyte chars

### ISSUE THREAD

**Issue by roooodcastro** [oesmith/puffing-billy#233]
Hello,

I'm trying to stub a JSON request, doing it like so:

```ruby
hash = { localidade: 'Niterói', bairro: 'Icaraí' }
proxy.stub(url).and_return(headers: { 'Access-Control-Allow-Origin' => '*' }, json: hash)
```

However, when I send this request (using chrome), I get the json response without the last two characters. This is what I'm getting:

    {"bairro":"Icaraí","localidade":"Niterói

What I think is happening is that somewhere, these two multibyte chars are being counted as a single byte char, and the response is being truncated to the length of the string without the multibyte chars. The missing text from the response is exactly 2 bytes long, consisting of the last double quote and curling brace.

**Comment by ryan-plated** [comment]
I was looking into this deeper I think this may be an event machine bug. What version of ruby are you using?

**Comment by jakepark** [comment]
```You can just use the github version in you Gemfile to fix this situation:

gem 'eventmachine_httpserver', git: 'https://github.com/eventmachine/evma_httpserver', require: 'evma_httpserver'
gem 'puffing-billy'
```
I can confirm this fixes an issue I have had. One JSON response was malformed by a few characters. It was driving me to insanity and I didn't want to blaim PuffingBilly. 

I could provide sample JSON fixtures to reproduce this issue but as said before it's not a fault in this gem.

**Comment by ronwsmith** [comment]
See workaround above.
