### ISSUE TITLE
Puffing Billy hanging tests

### ISSUE THREAD

**Issue by bitscraps** [oesmith/puffing-billy#238]
Im trying to implement puffing billy on cucumber but on install when ever i run a test that uses the selenium_billy driver it just seems to hang.

This is the billy parts of my config:

```
require 'billy/capybara/cucumber'

Billy.configure do |config|
  config.logger = Logger.new(File.expand_path('../../../log/billy.log', __FILE__))
end

Before('@billy') do |_scenario|
  Capybara.current_driver = :selenium_billy
end
```

When i run the test it gets through my first steps which are setup but when it gets to a step which interacts with the browser it appears to freeze.

update: I believe i've tracked it to the proxy.start call which is causing it to hang

Im not sure what I'm setting up wrong or if its a bug within billy

**Comment by ronwsmith** [comment]
Do you get any further with the other registered drivers?  `:selenium_chrome_billy`, `:poltergeist_billy`, or `:webkit_billy`

**Comment by bitscraps** [comment]
I've tried :poltergeist_billy as well but get the same issue

**Comment by ronwsmith** [comment]
Looks like we have some EventMachine logging [here](https://github.com/oesmith/puffing-billy/blob/master/lib/billy/proxy.rb#L43-L60).  Are you able to see anything in the logs?

**Comment by ronwsmith** [comment]
Closing, stale issue.

**Comment by kceb** [comment]
I'm experiencing something similar. Sometimes when I exit out of specs and restart the spec, rspec seemingly freezes and never completes.
