### ISSUE TITLE
Sequence support

### ISSUE THREAD

**Issue by simonoff** [oesmith/puffing-billy#243]
Hello!
We have case where we need to check a sequence of requests and store all of them into one file like VCR is working. Right now we still have a few POST requests which cannot be cached right now.

**Comment by jakepark** [comment]
If the issue still exists I would recommend writing a more detailed scenario, things that you've tried, research that you've come across.

If you fixed the issue, I'd suggest adding what you did to solve your particular use case scenario - and then submitting a PR to the README, perhaps. 

(i'm not a maintainer, just a suggestion)

**Comment by ronwsmith** [comment]
@simonoff sorry to say but this would be too big of a change to likely ever be implemented.  The gem caches URLs agnostic to particular specs.

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen if this is still desired.
