### ISSUE TITLE
Hanging/unable to connect when using selenium_chrome_billy driver

### ISSUE THREAD

**Issue by bcharna** [oesmith/puffing-billy#250]
I was noticing some hanging and errors when using the `selenium_chrome_billy` driver in my own app, so I decided to see if the same issue happens in the gem's test suite and it seems it does.

First, I simplified the gem's `spec_helper.rb` just to eliminate some completely for this exercise to the following:
```
Dir[File.expand_path('../support/**/*.rb', __FILE__)].each { |f| require f }

require 'pry'
require 'billy/capybara/rspec'
require 'billy/watir/rspec'
require 'rack'
require 'logger'
require 'fileutils'

Capybara.app = Rack::Directory.new(File.expand_path('../../examples', __FILE__))
Capybara.server = :webrick
Capybara.javascript_driver = :poltergeist_billy

Billy.configure do |config|
  config.logger = Logger.new(File.expand_path('../../log/test.log', __FILE__))
end
```

Note that I kept `Capybara.javascript_driver = :poltergeist_billy`.

**Then, a spec file is run:**

```
bundle exec rspec spec/features/examples/tumblr_api_spec.rb
```

**Output**
```
..

Finished in 1.44 seconds (files took 0.76901 seconds to load)
2 examples, 0 failures
```

This output is correct and as expected.

However, changing `Capybara.javascript_driver = :poltergeist_billy` to `Capybara.javascript_driver = :selenium_chrome_billy` causes the following output when the same command is run:

```
FF

Failures:

  1) Tumblr API example without scope external references should show news stories
     Failure/Error: visit '/tumblr_api.html'

     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:9523
     Shared Example Group: "tumblr/expectations" called from ./spec/features/examples/tumblr_api_spec.rb:39
     # ./spec/features/examples/tumblr_api_spec.rb:11:in `block (2 levels) in <top (required)>'

  2) Tumblr API example with scope external references should show news stories
     Failure/Error: visit '/tumblr_api.html'

     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:9523
     Shared Example Group: "tumblr/expectations" called from ./spec/features/examples/tumblr_api_spec.rb:63
     # ./spec/features/examples/tumblr_api_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 40.41 seconds (files took 0.73721 seconds to load)
2 examples, 2 failures
```

Any insight into why just changing the driver to `selenium_chrome_billy` causes the suite to not pass with the above errors?

**Comment by ronwsmith** [comment]
Looks like you may be missing the chromedriver itself.  We use the [chromedriver-helper](https://github.com/flavorjones/chromedriver-helper) gem in our projects.

**Comment by ronwsmith** [comment]
@bcharna has this issue been resolved for you?

**Comment by bcharna** [comment]
Yeah, last time I revisited this, I did not encounter the issue. Thank you!
