### ISSUE TITLE
ActionCable sockets not connecting with selenium_chrome_billy driver

### ISSUE THREAD

**Issue by frostblooded** [oesmith/puffing-billy#252]
I am using the selenium_chrome_billy driver for testing with Capybara. I have some ActionCable sockets, but they are not able to connect from the client side to the Rails server. This issue is not present when using the selenium_chrome driver.

In the console the websockets give the following message:

WebSocket connection to 'ws://127.0.0.1:44643/cable' failed: Connection closed before receiving a handshake response

**Comment by ronwsmith** [comment]
Do you see anything prefixed with `Billy` in the logs?

**Comment by frostblooded** [comment]
I am seeing a lot of things prefixed with `puffing-billy`, but they are all for HTTP requests like `puffing-billy: PROXY GET succeeded for 'https://ajax.googleapis.com:443/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css'`. Unfortunately I don't see any requests to 127.0.0.1:3000/cable or anything similar, which is the URL to which the socket connects.

In the logs I see only HTTP requests. As far as I know ActionCable uses WebSockets, which are different, but I am not sure how puffing-billy handles them.

I am having a brief discussion [on Reddit](https://www.reddit.com/r/rails/comments/9f8agm/puffing_billy_and_action_cable_error/?utm_content=full_comments&utm_medium=message&utm_source=reddit&utm_name=frontpage) with someone that has encountered this problem, but I couldn't quite make his solution work.

**Comment by frostblooded** [comment]
If this is of any help, in the browser console I am seeing an error

`WebSocket connection to 'ws://127.0.0.1:45801/cable' failed: Connection closed before receiving a handshake response`

and a warnings after that when it retries the connection

`WebSocket connection to 'ws://127.0.0.1:45801/cable' failed: WebSocket is closed before the connection is established.`

**Comment by ronwsmith** [comment]
Can you share your billy config?

**Comment by frostblooded** [comment]
I don't have anything configured. I suppose I am using the defaults.

**Comment by ronwsmith** [comment]
Please read through the README, especially this section: https://github.com/oesmith/puffing-billy#caching

**Comment by frostblooded** [comment]
Maybe I am completely misunderstanding something, but I am not sure what this problem has to do with caching. I am reading though the options, but I don't understand what I need from there for the websocket connection that doesn't even get logged.

**Comment by frostblooded** [comment]
I am trying to stub a direct upload to S3 and I have done that, but I also have ActionCable sockets on my site and for some reason they give these errors when using the puffing billy driver. I would like to have the direct uploads stubbed while also having the sockets to my server work.

**Comment by ronwsmith** [comment]
Hmm, I'm not familiar with ActionCable sockets so I'm not sure how much help I can be.  Have you tried to disable the caching?  Do you get the same error with other drivers that use puffing-billy?

**Comment by frostblooded** [comment]
I disabled the cache with

`Billy.configure do |c|
#   c.record_requests = true
  c.cache = false
  c.cache_request_headers = false
  c.persist_cache = false
  c.ignore_cache_port = false # defaults to true
  c.non_successful_cache_disabled = true
  c.cache_path = 'spec/req_cache/'
  c.proxy_host = 'localhost' # defaults to localhost
  c.proxy_port = 12345 # defaults to random
  c.proxied_request_host = nil
  c.proxied_request_port = 80
end`

Unfortunately that didn't change anything.
The normal JS drivers work correctly (selenium, selenium_chrome), but the selenium_billy driver doesn't even show the socket connection and the selenium_chrome_billy is the one with the original problem in this ticket.

As far as I know, the HTTP request that needs to pass in order for the socket to connect is seen [here](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake).

If we don't find a solution to this, I might be able to solve my issues without this gem, but it would be nice to fix the problem.

**Comment by ronwsmith** [comment]
If you're not seeing the requests at all, the WebSocket must be bypassing the proxy completely.  There are some drivers that bypass proxies for localhost/127.0.0.1 intentionally.  I'd suggest looking into driver settings and see if you can force the WebSocket connections through a proxy and then use the Billy proxy manually (by just adding the proxy to your driver config as the gem does for the *_billy drivers [here](https://github.com/oesmith/puffing-billy/blob/master/lib/billy/browsers/capybara.rb)).

**Comment by ronwsmith** [comment]
@frostblooded is this still an issue for you?

**Comment by frostblooded** [comment]
I don't really understand how to do any of this. Sorry. I also am not using this gem any longer as I couldn't make this work.

Looking back on it though, I see that maybe it isn't expected for this gem to work with websockets as they work somewhat differently from normal HTTP request. I suppose it is okay to close this issue now if you think this is something that isn't supposed to be supported.

**Comment by another-dave** [comment]
I've hit a similar issue with [Pusher's JavaScript client](https://pusher.com/docs/channels/getting_started/javascript) which uses secure websockets to their server.

I bypassed them from the proxy by using my own Chrome driver instance and setting flags to 

* connect to PB proxy
* by pass for `wss://` scheme

#### `bill_setup.rb`

```ruby
Billy.configure do |c|
  c.proxy_port = 1234
  # … other config…
end
```

#### `spec_helper.rb`

```ruby
browser_options = Selenium::WebDriver::Chrome::Options.new(args: %w[
  # … other config args …
  proxy-server=http://localhost:1234
  proxy-bypass-list=wss://*
])
```

**Comment by zedtux** [comment]
I am hitting this issue too with my remote dockerized chrome instance. Unfortunately passing the `--proxy-bypass-list=ws://*` flag to the container doesn't fix it as I'm still seeing the error `Connection closed before receiving a handshake response`.
