### ISSUE TITLE
Does puffing billy work with System Test?

### ISSUE THREAD

**Issue by PuckmanXY** [oesmith/puffing-billy#269]
I'm new to testing stuff with Rails and I had to mock some browser requisitions (such as images), then I found puffing-billy but couldn't find how to set it up with System Test in the docs. Does it work with System Test?

**Comment by ronwsmith** [comment]
I'm not familiar with System Test.  Puffing-billy is implemented as a browser proxy so it should work as long as the driver supports adding proxy configuration.  You can use the Billy proxy directly in your driver config using `Billy.proxy.host` and `Billy.proxy.port` and see if it works.

**Comment by PuckmanXY** [comment]
I'm working on another feature on the code that does not need puffing-billy to be tested, but as soon as I get time I'll try to setup System Test to work with puffing-billy and give an update to this issue. Thanks a lot!

**Comment by melostbr** [comment]
It didn't work for me as system test, only with `feature` tests. I ended up creating a custom example group to set all the specifics for puffing_billy though.

**Comment by jtoy** [comment]
im running into he same issue, has anyone got this to work?

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen if this is still desired.
