### ISSUE TITLE
Can I somehow save Cache and not use it in my tests?

### ISSUE THREAD

**Issue by YosipVoloshchuk** [oesmith/puffing-billy#286]
Hi All!
I need to check that after some actions on UI side was sent api requests, I found that when I use cache = true in Billy.configure I can save all requests in some folder, but it will reuse all requests in my next steps. Can I somehow only write requests to folder and not reuse them?

**Comment by ronwsmith** [comment]
I think you can do this by changing `cache_path` for each scenario with `around` hooks.

**Comment by YosipVoloshchuk** [comment]
@ronwsmith Thanks for the answer, Can You please to clarify
I using Capybara+Cucumber, so I have scenarios like
- Open some page
- Create some object
- Check that object is created
Right now when I am on last step I didn't see new object because page was cached without this object. All this steps it is 1 scenario. So | need to change cache_path for each step? Do You have some examples hove to use around hooks for it?

**Comment by YosipVoloshchuk** [comment]
I tried change cache_path after each step, but it is not help, on the last step requests are still reuse previous data that was cached

**Comment by ronwsmith** [comment]
Hmm, doesn't seem like it would work then.

**Comment by YosipVoloshchuk** [comment]
Ok. Thanks for answer
