### ISSUE TITLE
Feature request: instructions for using with selenium grid

### ISSUE THREAD

**Issue by snackattas** [oesmith/puffing-billy#305]
Can there be instructions for configuring a proxy to run in selenium grid? That would be hugely helpful for me :)

**Comment by ronwsmith** [comment]
Where does the browser run when using selenium grid?  Are there multiple browsers running?

**Comment by snackattas** [comment]
There's tons of different ways to define selenium grid. 
https://www.browserstack.com/guide/selenium-grid-tutorial

Basically, the browser can run either inside the same VM OR in a different VM, where, the tester process will send traffic to the selenium hub and the hub sends browser commands to the nodes. There are no doubt multiple browser nodes, and yea, they could ostensibly have multiple different kinds of browsers.

**Comment by ronwsmith** [comment]
Are you able to set driver settings for each of the running browsers?  If so, you can try setting the Billy host and port in the browser proxy settings.  Not sure if we'd need to run a Billy instance on each node though...

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen if this is still desired.
