### ISSUE TITLE
Net::ReadTimeout

### ISSUE THREAD

**Issue by ngouy** [oesmith/puffing-billy#311]
When working with subdomains, with or without me trying to whitelist my queries to my "localhost", I have Net::ReadTimeout only for my request to local subdomains

in my hosts file :

```
127.0.0.1 localhost my_subdomain.localhost.local_test
```

in my rails_helper:

```rb
config.around(:each, :feature_with_subdomain) do |example|
  when "system", "feature"
  default_host = Capybara.app_host
  Capybara.app_host = "http://my_subdomain.localhost.local_test"
  
  example.run
  
  Capybara.app_host = default_host
end

Billy.config.whitelist << /.*/
```

without the billy_selenium, it works, with the billy, it only works for request towards localhost, but not my custom subdomain. It just hang out for a wile and time out

**Comment by ronwsmith** [comment]
What does the rest of your Billy config look like?

Billy is a browser proxy, to handle client-side requests, it is not used for loading the app_host itself, which might be different behavior than you're looking for.

**Comment by ngouy** [comment]
Hey @ronwsmith, the config is the exact one above, I'm only whitelisting everything, so billy should let everything works as if it was not here

Sadly it doesn't work with my already existing subdomain configuration

**Comment by ronwsmith** [comment]
I'm not sure what you're attempting to do.  Are you looking to avoid using Billy for some of your tests?  It's implemented as a stub or a browser driver which it doesn't look like you're using.

**Comment by ngouy** [comment]
@ronwsmith I am trying to understand why it doesn't works for my current setup with subdomains.

The first step for me was trying to understand how does Billy works.
In my debugt proccess, one of the thing that felt wrong is the example I give here: Even bypassing everything, I still have an issue where I have inifite load.

The example I give here isn't the final usage I want for my project, but more of an:
"something is wrong, because even when I bypass everything, I have an issue that I don't have without Billy installed."

**Comment by ronwsmith** [comment]
From the config you provided, you're not using Billy at all, so the whitelist configuration change isn't doing anything.  If you are using the billy driver or stub anywhere, please include that information.

**Comment by ngouy** [comment]
No, that's exactly my point

I don't have the gem: My system specs are working
I install the gem, but bypass everything from Billy: It should just do nothing, but sadly, and that's the point of this ticket, it does something: my specs aren't working anymore (infinite load on my specs until it just time out)
the question of this ticket is "why?"

As I bypass everything, Billy should be transparent, and my specs should works just as before I install the gem.

**Comment by ronwsmith** [comment]
Again, your whitelist config line does nothing without the driver or proxy being used, so you are not "bypassing" anything.  The Billy proxy is lazy-loaded and won't start until it's used, so nothing is running at all.  I suspect something else is going on locally with gem dependency conflicts.

You can try checking the logs to see if you see Billy reporting any strange behaviors (but you likely won't unless you're initializing it somewhere that you haven't included).

**Comment by ngouy** [comment]
As I said, I'm using the driver.
> by transparent config I mean using the billy selenium driver, instead of the chrome one, and using the provided config where I whitelist everything

I will try to create a demo dummy app @ronwsmith 👍, this may be much more easier to understand

**Comment by ronwsmith** [comment]
Please include how and where you're using the driver and/or proxy stub.

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to reopen if this is still desired.
