### ISSUE TITLE
setting a proxy stub for regex urls

### ISSUE THREAD

**Issue by dezmathio** [oesmith/puffing-billy#32]
Currently, I can't seem to use regex to stub out requests to ad servers, such as 

proxy.stub(/doubleclick.net/).and_return(nil)

I'm coming from a WebMock background where I could just do

stub_request(:any, /doubeclick.net/)

and if I did any kind of Net::HTTP.get('http://blablabla.doubleclick.net/blabla', '/') 
it would return nil, b/c of the previous stub.

Any idea if this is possible w/ puffing-billy?

**Comment by ronwsmith** [comment]
Stale issue, closing.
