### ISSUE TITLE
Include lib/tasks/billy.rake

### ISSUE THREAD

**Issue by Aesthetikx** [oesmith/puffing-billy#320]
I think [this file](https://github.com/oesmith/puffing-billy/blob/9f54eb9f455ba7522a64de09f23badd3c6801434/lib/billy/railtie.rb) loads `lib/tasks/billy.rake`, however [this commit](https://github.com/oesmith/puffing-billy/commit/c7e19f1fc98c7a9adcf43fff60e21062c809e957) changed away from using git ls-files and no longer includes `lib/tasks/billy.rake`, which is raising an error on CI after upgrading to 3x. Not sure if that was intentional or not.

Best,
John

**Comment by ronwsmith** [comment]
Thanks @Aesthetikx !

@AlfonsoUceda can you take a look and see if we should revert that gemspec change?

**Comment by AlfonsoUceda** [comment]
Hey @Aesthetikx @ronwsmith sorry for that problem. What I would do instead is add that file to the gemspec.

**Comment by ronwsmith** [comment]
@AlfonsoUceda mind putting up a PR for that?  I'll release as 3.0.2

**Comment by AlfonsoUceda** [comment]
Yep, will do tomorrow

**Comment by Aesthetikx** [comment]
Thanks y'all, and no worries! Could have probably done it myself but it has been a while since I have worked with actual gems. Thanks for the hard work.

**Comment by ronwsmith** [comment]
@Aesthetikx please update to 3.0.2 and report back if that resolved your CI issues.

**Comment by Aesthetikx** [comment]
@ronwsmith All green! :green_apple: :green_book: :green_circle: :green_heart:
