### ISSUE TITLE
Breaks when upgrading selenium-webdriver from 4.10.0 to 4.11.0 (`headless!`)

### ISSUE THREAD

**Issue by uwe** [oesmith/puffing-billy#332]
`selenium-webdriver` removed the `headless!` method in 4.11.0 (https://github.com/SeleniumHQ/selenium/pull/12417).

`puffing-billy` is using it in https://github.com/oesmith/puffing-billy/blob/master/lib/billy/browsers/capybara.rb#L87.

**Comment by gustavosobral** [comment]
Hi @ronwsmith, perhaps you can help us here? I have open a PR that should fix this issue. 

At my team we were using https://github.com/titusfortner/webdrivers before but for the ChromeDriver v115 release onwards that gem recommends to just use `selenium-webdriver` 4.11+ now.

Let me know what do you think, thank you!!
