### ISSUE TITLE
WebMock and puffing-billy

### ISSUE THREAD

**Issue by dezmathio** [oesmith/puffing-billy#44]
I'm trying to set up puffing-billy on my local repo, and I'm running into a few issues. I am basically registering the webkit driver like this: 

Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app)
end

And then I am adding the @billy tag to my scenarios, and I've got a Before hook just like the one you guys have in the readme, which sets the current_driver and javascript_drivers to be :webkit_billy

Now, my issue is that if I visit a page when the driver is just :webkit
I take a screenshot, and everything looks proper, all the assets are there, it looks good.
However; When I run it tagged with @billy, or if I set the current_driver and javascript_driver's to be :webkit_billy, all of the assets are not rendered... 

I suspect it might be related to nginx, since the asset host is http://localhost:8089

I added this into a billy.rb file which is in features/support/

server = Capybara.current_session.server
Billy.config.whitelist = ["#{server.host}:#{server.port}/", 'http://localhost:8089']

Doesn't seem to help with my issue though. Should I add anything else beyond that? Am I missing some config settings to get this running properly with capybara-webkit?

just noticed @oesmith was active 20 min ago so I'm hoping to get someone's attention!

**Comment by jethroo** [comment]
```
 context 'with proxy', driver: :poltergeist_billy do
      scenario 'the user can share the link via facebook', billy: true do
      
end
```

```ruby  
config.around(:each, billy: true) do |example|
  WebMock.allow_net_connect!
  example.run
  WebMock.disable_net_connect!(allow_localhost: true)
end
```

**Comment by korbin** [comment]
Few years late, but just stumbled across this:

If you're not using EventMachine (or WebMock for any other EM requests):

```Ruby
WebMock::HttpLibAdapters::EmHttpRequestAdapter.disable!
```

in spec_helper.rb will disable WebMock's interception of EM HTTP requests, allowing upstream proxy requests to go through.

Pretty blunt, but it works.

**Comment by nullobject** [comment]
You can also do:

    WebMock.enable!(except: :em_http_request)

**Comment by 23tux** [comment]
Neither 

```
WebMock.enable!(except: :em_http_request)
```

nor

```
WebMock::HttpLibAdapters::EmHttpRequestAdapter.disable!
```

does work for me.

I import an external CSS file via `@import url("//hello.myfonts.com/XXXXXX");` at the bottom of my HTML file, and this causes a second request via `visit "/"` to only return this response by capybara:

```
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>
```

However, when I stub the request with Webmock it works:

```
    stub_request(:get, "hello.myfonts.com/XXXXXX")
```

I can work with this for now, but as soon as I would introduce a new request that gets proxied through Billy, it would break again silently causing trouble finding the root of the problem.

So any idea on how to fix this?
