### ISSUE TITLE
Silencing handle_request errors due to not being in the whitelist

### ISSUE THREAD

**Issue by dezmathio** [oesmith/puffing-billy#45]
Hey guys, so ... I wanted to use puffing-billy in a way where I can simply set a whitelist, and have it only allow requests to those host:port's.

So, when I set 
  Billy.config.non_whitelisted_requests_disabled = true
This basically makes my cucumber output return all of the puffing-billy error's from the handle_request method, it doesn't mess with my test at all, but I was wondering if there's a way to supress that, or a setting that I'm missing? 

I don't want to cache things, I'd prefer just not allowing external calls to be made, and ignoring the errors. 

Basically the errors that show up are like this: 

puffing-billy: Connection to http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700 not cached and new http connections are disabled
/Users/josiahanjos/.rvm/gems/ruby-2.1.0/bundler/gems/puffing-billy-47b7502bcb1e/lib/billy/proxy_connection.rb:65:in `block (2 levels) in handle_request'
/Users/josiahanjos/.rvm/gems/ruby-2.1.0/bundler/gems/puffing-billy-47b7502bcb1e/lib/billy/proxy_connection.rb:62:in `tap'
/Users/josiahanjos/.rvm/gems/ruby-2.1.0/bundler/gems/puffing-billy-47b7502bcb1e/lib/billy/proxy_connection.rb:62:in `block in handle_request'
/Users/josiahanjos/.rvm/gems/ruby-2.1.0/gems/em-synchrony-1.0.3/lib/em-synchrony.rb:29:in `block in synchrony'
RuntimeError

I read the description for the c.non_whitelisted_requests_disabled and you guys say it's intended for debugging, which makes sense. 
But in my case, I think it'd be preferable to have a whitelist, instead of a blacklist, or a list of stubs to external requests. 
Would it be possible to add a new config line with... c.suppressed_errors = false # default
Where if I set it to true, these errors aren't printed?

**Comment by ronwsmith** [comment]
Closing issue, conversation continues in the PR.
