### ISSUE TITLE
Built-in SSL certificate already expired

### ISSUE THREAD

**Issue by wulab** [oesmith/puffing-billy#48]
I can't get pass this screen when testing with Selenium (even after adding it to security exception). Facebook and Google sites seem not to be affected though. I guess the certificate in `lib/billy/mitm.crt` needs to be updated. Thanks.

![firefox](https://cloud.githubusercontent.com/assets/592709/2679596/b65ed9c2-c175-11e3-8ba3-bcd9b853774e.png)

 Tested on Firefox v28.0.

**Comment by ronwsmith** [comment]
@wulab, please test out the change in PR #85.
