### ISSUE TITLE
Minitest support

### ISSUE THREAD

**Issue by elfassy** [oesmith/puffing-billy#49]
Does this gem work with minitest? Thanks

**Comment by ronwsmith** [comment]
@elfassy, looks like puffing-billy will work with [minitest-rails-capybara](https://github.com/blowmage/minitest-rails-capybara).  You just need to [specify the driver](https://github.com/blowmage/minitest-rails-capybara#specifying-drivers) to use one of the *_billy versions.

Please try it out and report back.  If it works well, we can update the README with a `Minitest Usage` section.

**Comment by sauy7** [comment]
I gave this a shot and extracted this gist... https://gist.github.com/sauy7/1b081266dd453a1b737b

It could probably use some tidying up but it might help someone get started.

**Comment by ronwsmith** [comment]
Thanks @sauy7, I'll add that link to the README.

**Comment by nijotz** [comment]
I'm trying to get billy working with minitest.  I keep getting `uninitialized constant Billy::RequestHandler::Forwardable (NameError)` just trying to do `require 'billy'`, even straight from irb.

**Comment by nijotz** [comment]
Looks like adding `require 'forwardable'` to `.../puffing-billy-0.5.1/lib/billy/handlers/request_handler.rb` fixed it.  This may be another issue regarding ruby version compatibility.  I'm using ruby 2.2.1

**Comment by ronwsmith** [comment]
Good catch, looks like that should be a runtime dependency.

Please submit a PR if you get a chance.  Thanks!

**Comment by nijotz** [comment]
This seems a separate issue.  I'll create a new one.  I did get puffing-billy working with minitest, fyi.

**Comment by nijotz** [comment]
I opened #108 for the problem I was running into integrating this with minitest

**Comment by ronwsmith** [comment]
Update to v0.6.1 for this support.

**Comment by jduffy3** [comment]
Could you update the docs with the setup for MiniTest? 🥲
