### ISSUE TITLE
Allowing pass through for certain URLs

### ISSUE THREAD

**Issue by conatus** [oesmith/puffing-billy#53]
Hi there,

Amazing product. 

As far as I can see there is no way of doing a "partial" mock - only caching certain services and then passing through for other services. `Billy.config.non_whitelisted_requests_disabled` will cause an error to be thrown but the behaviour I want is for something like `Billy.config.mock_request_paths` and only things on that list will be cached - everything else will pass through.

This is in order to prevent stuff I don't really care about like images from being cached. Bonus round: smarter regex for excluding categories of things.

Willing to work on this, just wondered if anyone else was.

**Comment by ronwsmith** [comment]
Stale issue, closing.  Double-checked the README and it seems clear to me.

Please submit a PR with more clarifications if you get a chance.
