### ISSUE TITLE
Options for poltergeist

### ISSUE THREAD

**Issue by lencioni** [oesmith/puffing-billy#61]
I would like to use puffing billy with poltergeist, but with the `js_errors` option turned on. It would be nice if there was a way for me to set some options that are passed through to poltergeist in the `register_drivers` call.

The list of poltergeist options can be found at: https://github.com/teampoltergeist/poltergeist#customization

**Comment by tansaku** [comment]
@trotzig - any chance you could share your precise config?  I'm trying to use @ronwsmith's above but get: 

Error: Unknown option: js_errors

**Comment by ronwsmith** [comment]
@tansaku, this is my current config:

```ruby
   Capybara.register_driver :pg_billy do |app|
     options = {
       js_errors: false,
       phantomjs_options: [
         '--ignore-ssl-errors=yes',
         "--proxy=#{Billy.proxy.host}:#{Billy.proxy.port}"
       ]
     }
     Capybara::Poltergeist::Driver.new(app, options)
   end
```

**Comment by tansaku** [comment]
@ronwsmith - much appreciated

**Comment by trotzig** [comment]
@tansaku it looks like you were helped above. I had a quick look at our current configuration, and it looks like we no longer register a custom driver. I could do some digging in our git log but I'd prefer not to. :)

**Comment by ronwsmith** [comment]
See workaround above or someone can help take https://github.com/oesmith/puffing-billy/pull/234 over the finish line
