### ISSUE TITLE
HTTP Basic Auth credentials are being stripped

### ISSUE THREAD

**Issue by almostwhitehat** [oesmith/puffing-billy#63]
I've been testing puffing billy against a site which requires basic auth. When I make requests with the credentials in the URL (http://username:password@domain.com) the basic auth credentials are not being passed to the domain.com server.

**Comment by ronwsmith** [comment]
@almostwhitehat I created a [PR with support for basic auth](https://github.com/oesmith/puffing-billy/pull/88).

Can you test it out and let me know if that addresses your issue?

**Comment by ronwsmith** [comment]
Closing issue, please continue the conversation in the PR.
