### ISSUE TITLE
Rake tasks are not working

### ISSUE THREAD

**Issue by volkanunsal** [oesmith/puffing-billy#64]
I noticed there are a few rake tasks that are included by this gem, which I can see when I run `bundle exec rake -T`, but I cannot use them for whatever reason. Here is the error message I get:

     rake aborted!
     Don't know how to build task 'cache:find_non_successful'
     /Users/newuser/.rvm/gems/ruby-2.1.1@global/gems/rake-10.3.2/lib/rake/task_manager.rb:62:in `[]'

I'm using Ruby 2.1.1 and Rails 4.1.5

**Comment by ronwsmith** [comment]
Tried to recreate and wasn't able to on 2.1.5 / 4.1.0.  The only thing I could find that might cause this is if Rails isn't loaded when it's attempting to run: https://github.com/oesmith/puffing-billy/blob/master/lib/billy.rb#L12

**Comment by ronwsmith** [comment]
@volkanunsal, any update on this issue?
