### ISSUE TITLE
`c.ignore_urls` is not working

### ISSUE THREAD

**Issue by volkanunsal** [oesmith/puffing-billy#65]
It cannot ignore a url with a dynamic parameter, which is often the case with trackers. For example:

    https://api.mixpanel.com/track/?ip=1&img=1&data=eyJldmVudCI6ImNoZWNrb3V0Lm9wZW4iLCJwcm9wZXJ0aWVzIjp7InRva2VuIjoiZDc1MTNiMTZkNTY0OTE3MWYwNDVlY2Q5YTBkZTVjMWIiLCJ1c2VyQWdlbnQiOiJNb3ppbGxhLzUuMCAoTWFjaW50b3NoOyBJbnRlbCBNYWMgT1MgWCAxMC45OyBydjozMS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzMxLjAiLCJvcHRpb24tcmVmZXJyZXIiOiJodHRwczovLzEyNy4wLjAuMTozMDAxLyIsIm9wdGlvbi11cmwiOiJodHRwczovLzEyNy4wLjAuMTozMDAxLz9wbGFuPWdvbGQiLCJvcHRpb24tdGltZUxvYWRlZCI6MTQwOTY5Mzg5NCwib3B0aW9uLWtleSI6InBrX0tUeXM1YjdvMkVvTFlaNkJrUnhVRDFRZXFoRXZmIiwib3B0aW9uLW5hbWUiOiJSb2JvU3dlZXBlciIsIm9wdGlvbi1kZXNjcmlwdGlvbiI6IiQ0Ljk5L21vbnRoLiBGcmVlIGZvciBmaXJzdCAzMCBkYXlzLiIsIm9wdGlvbi1wYW5lbExhYmVsIjoiU3Vic2NyaWJlIGZvciIsIm9wdGlvbi1lbWFpbCI6InNwb2Nrc3BsYW5ldEBnbWFpbC5jb20iLCJvcHRpb24tYW1vdW50Ijo0OTksImRpc3RpbmN0X2lkIjoiNGQ5NWQzMDMtNzFkOS05NDYwLWE5NTItN2QwZDY2ODk2MzNmIiwic3QtdWktdHlwZSI6ImRlc2t0b3AiLCJzdC12YXJpYW50LXRyYWNpbmciOiJleGNsdWRlZCIsInN0LXZhcmlhbnQtcmVtZW1iZXJNZSI6ImV4Y2x1ZGVkIiwic3QtdmFyaWFudC1hdXRvY29tcGxldGUiOiJleGNsdWRlZCIsInN0LXZhcmlhbnQtcGhvbmVWZXJpZmljYXRpb24iOiJleGNsdWRlZCIsInN0LXZhcmlhbnQtcGhvbmVWZXJpZmljYXRpb25Db3B5IjoiZXhjbHVkZWQiLCJzdC12YXJpYW50LXBob25lVmVyaWZpY2F0aW9uUGF5IjoiZXhjbHVkZWQiLCJzdC12YXJpYW50LWFkZHJlc3MiOiJleGNsdWRlZCIsInN0LXZhcmlhbnQtanN1bml0IjoiZXhjbHVkZWQiLCJzdC1hY2NvdW50cy1lbmFibGVkIjp0cnVlLCJzdC1yZW1lbWJlci1tZS1lbmFibGVkIjp0cnVlLCJzdC1yZW1lbWJlci1tZS1jaGVja2VkIjpmYWxzZSwic3QtYWNjb3VudC1jcmVhdGVkIjpmYWxzZSwic3QtbG9nZ2VkLWluIjpmYWxzZSwic3QtdWktaW50ZWdyYXRpb24iOiJpZnJhbWUiLCJoIjo5MDAsInciOjE0NDB9fQ==

**Comment by ronwsmith** [comment]
@volkanunsal, did that setting work for you?

**Comment by volkanunsal** [comment]
I think it did. Thanks.
