### ISSUE TITLE
 undefined method `dynamic_jsonp='

### ISSUE THREAD

**Issue by volkanunsal** [oesmith/puffing-billy#66]
For some reason I cannot fathom, I have been getting an error that suggests that `dynamic_jsonp` and `dynamic_jsonp_key` methods are not defined in the configuration class. I confirmed that they aren't defined by prying into the code during execution, but the gem source clearly shows they are being made available by `attr_accessor` method. The specs of the gem are passing for that particular call, and this is only happening when the configuration is being set up. Does anyone have any ideas?

**Comment by ronwsmith** [comment]
@volkanunsal, a new gem was recently cut with the `jsonp` support.  Please update and re-open issue if you run into any problems.
