### ISSUE TITLE
Caching stubbed responses

### ISSUE THREAD

**Issue by BlueVajra** [oesmith/puffing-billy#72]
We are running a separate api server(via nginx) from our app and making requests with a `/api/v1/endpoint/query` url. When running Capybara, it won't recognize that endpoint because it is running on a different server. We found PuffingBilly to stub out all of those queries... great so far.

The caching of external api requests seems like a great option, but since our api endpoint is on the same host, capybara can't find it and we can't cache the real data.  We found a sneaky way of getting data by using the `proxy.stub(http://127.0.0.1:9887/api/v1/analytics/query').and_return(Proc.new { |params, headers, body|` to proxy any api requests and then making a Net::HTTP request to a live server and returning the actual json data.

The problem with this is that PuffingBilly will not cache the response. Any thoughts on handling this or forcing PB to cache the stubbed response? Or maybe just using the proxy without the stub?

**Comment by romanlehnert** [comment]
I tryied to to this by adding to my billy config. 
```ruby
c.path_blacklist = ['http://127.0.0.1/admin/api/v1/translations/']
```

Unfortunately, it seems that poltergeist does currently not allow to pipe requests to localhost to a proxy: https://github.com/ariya/phantomjs/issues/11342

There is an open PR for that: https://github.com/ariya/phantomjs/pull/12703

**Comment by BlueVajra** [comment]
@ronwsmith I feel like I did try it, but have been away from this project for a bit. I will give it a try and check back in. It may have been the same poltergeist issue as above, not sure.

**Comment by ronwsmith** [comment]
@romanlehnert, try it without the domain as the check is [purely against the path](https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/proxy_handler.rb#L101-103)

If that doesn't work and poltergeist may be to blame, you can try using the `webkit_billy` driver.

**Comment by ronwsmith** [comment]
@BlueVajra, just wanted to check in with you to see if that setting worked for you.

**Comment by ronwsmith** [comment]
@romanlehnert / @BlueVajra, either of you still having issues with path_blacklist?

**Comment by ronwsmith** [comment]
Closing -- stale issue.
