### ISSUE TITLE
Cache persistance not working

### ISSUE THREAD

**Issue by anero** [oesmith/puffing-billy#75]
We're having some issues when trying to integrate puffing-billy with a rails 3.2 app and we haven't been able to figure out if it's because I'm using the lib wrong or if it's an actual bug.

We're using puffing-billy on a scenario that visits a page with a form that uses Google Maps JS API's autocomplete component, fills the fields and selects one of the options from the autocomplete, and submits the form. Our goal would be to be able to:
* Retrieve the JS library from Google, to be able to detect any breaking changes on the library on the integration tests.
* Persist the cache of a real call, since stubbing Google's responses would be too complex.

We're using Capybara+RSpec+Webkit (headless)+WebMock for our integration tests, and our current configuration looks like this:

```ruby
RSpec.configure do |config|
   ...
   # Switch the drivers when a feature or scenario is marked with 'mock_js'
   config.around :each do |example|
    if example.metadata[:mock_js]
      Capybara.javascript_driver = :webkit_billy
      Capybara.current_driver = :webkit_billy

      example.run

      Capybara.current_driver = :webkit
      Capybara.javascript_driver = :webkit
    else
      example.run
    end
  end
end

Billy.configure do |c|
  c.cache = true
  c.cache_request_headers = false
  c.path_blacklist = []
  c.persist_cache = true
  c.ignore_cache_port = true # defaults to true
  c.non_successful_cache_disabled = false
  c.non_successful_error_level = :warn
  c.non_whitelisted_requests_disabled = false
  c.cache_path = 'scenarios/puffing-billy/req_cache/'
end

Capybara.javascript_driver = :webkit_ignore_ssl
```

When running the scenario, the cache for the Google Maps API call is not persisted.
If we don't stub the call to Google Maps API endpoint, it fails to retrieve some assets (though strangely it works for others). Below is a snippet from the `test.log` file

```
puffing-billy: CACHE KEY for 'http://127.0.0.1:64858/assets/events.css' is 'get_127.0.0.1_2eb19e129e8b4d150b9934508d1a60792d9be7cc'
puffing-billy: PROXY GET for 'http://127.0.0.1:64858/assets/events.css'
puffing-billy: Request failed: http://127.0.0.1:64858/assets/events.css
```

If we include the stub for Google Maps API JS call, all assets are retrieved correctly from localhost. I guess we could manually stub the responses from Google, but we wouldn't be able to accomplish the goals listed above... The log for the run with the stubbed Google call regarding the failing assets from the previous example is:

```
puffing-billy: CACHE KEY for 'http://127.0.0.1:65337/assets/events.css' is 'get_127.0.0.1_2eb19e129e8b4d150b9934508d1a60792d9be7cc'
puffing-billy: PROXY GET for 'http://127.0.0.1:65337/assets/events.css
```

In neither of the examples the cache is persisted on the defined directory (though I think it's expected in the latter case given that we're stubbing all calls to our only external dependency).

**Comment by ronwsmith** [comment]
@anero, a new gem has been released, please update and report back with any additional logging.  Thanks!

**Comment by anero** [comment]
@ronwsmith thank you for following up. I resumed work on this last week and was able to find the issue: there was a hidden call to Webmock `disable_net_connect!` that was forbidding connections to Google Maps, though I only noticed it when debugging and manually running EM's request at https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/proxy_handler.rb#L20, the exception didn't seem to get logged which made it hard to find the underlying issue.

**Comment by ronwsmith** [comment]
@anero, ah ha, thanks for the update.

Can you try running this to see if it's returns `false` before your fix?  If so, I can add a return error with it:

`defined?(WebMock) && WebMock.net_connect_allowed?(url)`

**Comment by ronwsmith** [comment]
@anero, just wanted to check in to see if you were able to try that step and think it's worthwhile to add that check.

**Comment by ronwsmith** [comment]
@anero, any updates here or are we good to close this issue?

**Comment by anero** [comment]
Hey, thanks for checking in! Unfortunately we decided not to move forward on this project so I've nothing else to add to this issue. 
Closing now & once again much appreciated for your interest on seeing this through!
