### ISSUE TITLE
Nested attributes with dynamic_jsonp_keys

### ISSUE THREAD

**Issue by michaelrkn** [oesmith/puffing-billy#79]
I'm using the Balanced Payments API in a project. A typical request has parameters that look like this (converted to JSON for readability):

```
"data": {
  "name": "Example Brown 1",
  "number": "4111111111111111",
  "expiration_month": "12",
  "expiration_year": "2020",
  "cvv": "123",
  "address": {
    "postal_code": "11211"
  },
  "meta": {
    "capabilities_system_timezone": -8,
    "capabilities_user_agent": "Mozilla\/5.0 (Macintosh; PPC Mac OS X) AppleWebKit\/534.34 (KHTML, like Gecko) PhantomJS\/1.9.7 Safari\/534.34",
    "capabilities_language": "en-US",
    "capabilities_kp": 45,
    "capabilities_cli": 1,
    "capabilities_loaded": 1418668507849,
    "capabilities_screen_width": 2560,
    "capabilities_screen_length": 1440,
    "capabilities_hist": 1,
    "capabilities_cookie": "1418668507849.7760353146586567.1!0",
    "capabilities_cl": false,
    "capabilities_submitted": 1418668507899,
    "capabilities_scrollX": 0,
    "capabilities_scrollY": 0
  }
}
```

Because all of the keys are nested within the "data" key, using `dynamic_jsonp_keys` is very blunt - I have to either ignore everything or nothing. It would be nice to be able to specify nested keys to ignore, e.g.:

```
Billy.configure do |c|
  c.dynamic_jsonp_keys = ["callback", "data"["meta"]]
end
```

or something along those lines. I'm not exactly sure what the right interface would be. 

The relevant code is at https://github.com/oesmith/puffing-billy/blob/master/lib/billy/cache.rb#L99.

**Comment by ronwsmith** [comment]
@michaelrkn, whoa, Balanced Payments sends credit card details in the GET query string?  That violates nearly every rule about [when to use a GET](http://www.w3schools.com/tags/ref_httpmethods.asp).  I haven't seen nested GET params in a very long time and have reservations about helping enable Balanced Payments' poor architecture if that's indeed the case.

**Comment by michaelrkn** [comment]
Because the balanced.js library uses JSONP, it creates an async `<script>` tag to send the information and execute the callback:

```
function jsonp(path, callback) {
    var funct = "balanced_jsonp_" + Math.random().toString().substr(2);
    var tag = document.createElement("script");
    tag.type = "text/javascript";
    tag.async = true;
    tag.src = path.replace("{callback}", funct);
    var where = document.getElementsByTagName("script")[0];
    where.parentNode.insertBefore(tag, where);
    window[funct] = function(result) {
        try {
            callback(result);
        } catch (e) {
            if (typeof console !== "undefined" && console.error) {
                console.error(e);
            }
        }
        tag.parentNode.removeChild(tag);
    };
}
```

So, yes, it is performing a GET request, but that's because it's using JSONP. Honestly, I didn't actually understand how JSONP until doing a bit of research just now, but this seems to be the standard way to make requests with JSONP.

**Comment by ronwsmith** [comment]
@michaelrkn, is this still an issue?  I see that the related issue in your repo was closed in June.

**Comment by michaelrkn** [comment]
We switched from Balanced to Stripe and no longer need to ignore nested keys. I have no idea if Puffing Billy supports this now, but my feelings won't be hurt if you decide this isn't important and close the issue :)

**Comment by ronwsmith** [comment]
I'll close it for now until another Balanced user runs into the same issue.
