### ISSUE TITLE
Ignoring google maps and cache.

### ISSUE THREAD

**Issue by rafael** [oesmith/puffing-billy#8]
Hi,

I have a question. I'm trying to use the cache but I'm having some issues with google maps. There are some files that always get regenerated and I'm not exactly sure how to ignore them.  I tried to add https://maps.google.ca/maps to the ignore list. But it didn't work.

Have you tried to ignore google maps parameters in the past? Do you have some insight here?

Thanks in advanced for your help.

**Comment by ronwsmith** [comment]
Stale issue, closing.  Feel free to re-open with more details.
