### ISSUE TITLE
URI::InvalidURIError bad URI(is not URI?)

### ISSUE THREAD

**Issue by richbits** [oesmith/puffing-billy#80]
I am receiving the following error when running tests with puffing-billy:

`URI::InvalidURIError
bad URI(is not URI?): https://fonts.googleapis.com:443/css?family=Cabin+Sketch:400,700|Love+Ya+Like+A+Sister`

This error is occurring in  /lib/billy.cache.rb line 90 format_url method. The line `url = URI(url)` raises the exception because of the '|' [pipe] character in the URL. This is valid, but causes the exception. 

By changing the line to `url = URI.parse(URI.encode(url.strip))` a valid URI object is returned. 

In the meantime, I have encoded the '|' within my html file as: `<link href='https://fonts.googleapis.com/css?family=Cabin+Sketch:400,700%7CLove+Ya+Like+A+Sister' rel='stylesheet' type='text/css'>`

**Comment by ronwsmith** [comment]
I ran into issues with your fix because it also encodes `#` for anchors/URL fragments.  I also think that fix would have double-encoded your workaround URL.

I switched to using Addressable and it fixes your issue.
