### ISSUE TITLE
When deleting the cache, all tests hang in Cucumber

### ISSUE THREAD

**Issue by plicjo** [oesmith/puffing-billy#90]
Hey guys, whenever I delete my cache and run all my tests, all of my `@puffing-billy` Cucumber tests hang up for a very long time and fail. I'm using the cache with VCR setup.

Here's my config:

```
Billy.configure do |c|
  c.cache = true
  c.cache_request_headers = false
  c.ignore_params = ["http://www.google-analytics.com/__utm.gif",
                     "https://r.twimg.com/jot",
                     "http://p.twitter.com/t.gif",
                     "http://p.twitter.com/f.gif",
                     "http://www.facebook.com/plugins/like.php",
                     "https://www.facebook.com/dialog/oauth",
                     "http://cdn.api.twitter.com/1/urls/count.json",
                     "http://get_maps.gstatic.com",
                     "http://get_fonts/googleapis.com",
                     "http://get_maps.googleapis.com"]
  c.path_blacklist = []
  c.persist_cache = true
  c.ignore_cache_port = true # defaults to true
  c.non_successful_cache_disabled = false
  c.non_successful_error_level = :warn
  c.non_whitelisted_requests_disabled = false
  c.cache_path = 'features/support/request_cache/'
end
```

I added this line before the config to try and get Billy to reset itself: `Billy.proxy.reset_cache`

I get this error:

```
Timed out waiting for response to {"name":"visit","args":["http://127.0.0.1:61200/employment_emails/new"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
```
The only way to get it to run properly is to uninstall and reinstall `puffiing-billy`,`vcr`, and `webmock`. Any thoughts?

**Comment by ronwsmith** [comment]
Seems like it's either your internet access wherever this is running, or some race condition between the gems that are blocking each other.

Can you also share any before/after blocks in your `spec/rails_helper.rb`?  Also, anything in the Billy log?

**Comment by plicjo** [comment]
I figured out that `puffing-billy` doesn't like it when you delete the cache from under it. I just uninstalled and reinstalled the gem and left the cache alone.

It's an edge-case issue I don't have any idea how to fix. Closing this.
