### ISSUE TITLE
Missing slash causes visit to skip proxy

### ISSUE THREAD

**Issue by ahallock** [oesmith/puffing-billy#92]
The following skips the BIlly proxy on `visit`:
```
proxy.stub('http://example.com').and_return(:text => 'Foobar')`
visit 'http://example.com'
```

But if I use "http://example.com/" it will return 'Foobar'. Perhaps this an issue in phantomjs. It seems like either form should work the same.

**Comment by ronwsmith** [comment]
Agreed.  Does it have the same behavior for all drivers?  This will help narrow down where the issue is.

We may be able to fix it either way.  If you get a chance, add some logging around all `url`s in these two files and see where the slash is being added to the stub:
```
https://github.com/oesmith/puffing-billy/blob/master/lib/billy/handlers/stub_handler.rb
https://github.com/oesmith/puffing-billy/blob/master/lib/billy/proxy_request_stub.rb
```

**Comment by ahallock** [comment]
@ronwsmith I'll have some time next weekend to test the various drivers.

**Comment by ronwsmith** [comment]
@ahallock, any luck narrowing this down more?

**Comment by ronwsmith** [comment]
@ahallock, any updates for this issue?

**Comment by ahallock** [comment]
@ronwsmith I don't have any updates--my contract ended on that project. My apologies.

**Comment by ronwsmith** [comment]
Closing -- stale issue.  Feel free to comment if this occurs for anyone else.
