### ISSUE TITLE
Modifying cached responses

### ISSUE THREAD

**Issue by drewbaumann** [oesmith/puffing-billy#95]
Hello,
I have been working on creating specs for a couple different scenarios my scraper may come upon. To emulate these situations I had planned to change the content of a page cached with puffing-billy. However it seems like I receive an error from my scraper whenever I change the content. How can I change the content of the cache without failure?

**Comment by ronwsmith** [comment]
I can't help much without the specific error, but in general, I don't think you should be trying to modify cache on the way back through.  It sounds like you should be using the proxy stubbing feature where you specify the exact response you want and you can create specs around those scenarios.

**Comment by drewbaumann** [comment]
Thanks. I don't believe I would have been able to do that based on the way the ajax response was handled, but it is a fine suggestion and something I have not tried. I'm going to close this as it may be unique to the website I was caching.
